### ISSUE TITLE
Only Shows Default Windows Logo

### ISSUE THREAD

**Issue by thedroidgeek** [Metabolix/HackBGRT#1]
I gave this tool a try yesterday on my ASUS X751LK laptop but all it did is make the default Windows logo show instead of the OEM one. I'm on Windows 10 Pro.

**Comment by Metabolix** [comment]
Thanks for reporting.

If you're now getting the Windows logo, the at least the BGRT was changed or removed.

Possible reasons for getting the Windows logo:
- `image=remove` in config.txt (this is a supported feature)
- missing BMP file; an error should be shown for 1 second, though
- invalid BMP file; the supported format is very limited
- possibly too big BMP? [TODO: try this one!]
- something weird

If you have modified any of the files, please uninstall and retry with the defaults. If that doesn't work, please check if `image=black` in config.txt produces a black background.

**Comment by thedroidgeek** [comment]
I had the same result with the original files, and `image=black` didn't work as well.
I also manually checked the EFI partition and all files were there.

**Comment by Metabolix** [comment]
See [issue-1-try-1.zip](https://github.com/Metabolix/HackBGRT/files/264437/issue-1-try-1.zip) for two versions of `bootx64.efi` to try out:
- `bootx64-git-b5006f7.efi`: the current Git version with minor fixes. Add `debug=1` in `config.txt` and see if there's any evident errors. The ACPI tree is relevant only if there are either zero or multiple BGRT entries.
- `issue-1-try-1.bootx64.efi`: preserves OEM ID and other seemingly irrelevant information in the BGRT. (See the included patch.) Interesting to see if this actually makes a difference.

Maybe I should add better debugging capabilities...

**Comment by thedroidgeek** [comment]
Still the same result for both files, there's been no error [as far as I can tell](http://i.imgur.com/fXoYqQ0.gifv).

**Comment by Metabolix** [comment]
Well, apparently you do have two sets of ACPI tables and two BGRT entries. I wasn't able to test this kind of configuration and made a guess that the second one could be deleted – apparently not? So here are two more tests: 2a uses the last BGRT entry, and 2b updates all of them. 
[issue-1-try-2.zip](https://github.com/Metabolix/HackBGRT/files/264516/issue-1-try-2.zip)

**Comment by thedroidgeek** [comment]
I can confirm only 2b works! So it seems all BGRT entries need to be updated.

**Comment by Metabolix** [comment]
Right, so I'll mainline that and probably fix something up for adding missing BGRT's as well. Thanks a lot for your help!

**Comment by Metabolix** [comment]
Fixing it properly took some refactoring, so I'd be grateful if you could test once more: [issue-1-try-3.zip](https://github.com/Metabolix/HackBGRT/files/264638/issue-1-try-3.zip)

If it works, it will be v1.0.1.

**Comment by thedroidgeek** [comment]
Works as it should. Thanks for the fix! :)

**Comment by Metabolix** [comment]
Fixed in v1.1.0.
