### ISSUE TITLE
New installer

### ISSUE THREAD

**Issue by Rikitav** [Metabolix/HackBGRT#103]
Hello, can I have the source code of the "Setup.exe" file for the new installer? I want to try myself and at the same time help you.
Please contact me gutii.ip.pl@gmail.com

**Comment by Rikitav** [comment]
The new installer will have a gui interface and a config generator!

**Comment by Rikitav** [comment]
HEY ! Im done without source code.
Creator, can you please see this!
https://drive.google.com/file/d/1-TI0vkJOnh2_7jo8NszjssuNzPgAP_Vo/view?usp=sharing
For other info contact me gutii.ip.pl@gmail.com

**Comment by Metabolix** [comment]
Source code is in the repository.
