### ISSUE TITLE
Back to basic boot logo

### ISSUE THREAD

**Issue by froggal** [Metabolix/HackBGRT#105]
I applied this on my SAMSUNG laptop. The current HACKBGRT logo is displayed as the Boot logo, how do I change it back to the default Boot logo of the SAMSUNG laptop?

**Comment by SebastianCompany-Norway** [comment]
Run the setu agaiin, type "R" to remove, press any key to finish, it exit. Now it's removed.

**Comment by SebastianCompany-Norway** [comment]
*setup again

**Comment by SebastianCompany-Norway** [comment]
PS: You can select the three dots at my comment and mark it as a answer.

**Comment by froggal** [comment]
> PS: You can select the three dots at my comment and mark it as a answer.

Yes

**Comment by SebastianCompany-Norway** [comment]
Alright! Hope you enjoy!
