### ISSUE TITLE
How do I uninstall it? 

### ISSUE THREAD

**Issue by LucasLy** [Metabolix/HackBGRT#106]
I've read the Recovery thing at the read me.
But I still don't understand anything I guess I have not as much in experience at this.
I have an HP computer a prodesk.
And I can't seem to find the original location of the boot file. Yes I can boot into the original EFI but I dont know which path it is. Hackbgrt says that it's on disk A but I don't any one?
And windows doesn't seem to find it too.
How do I find it? Please help!

**Comment by BackMountainDevil** [comment]
download the release.zip. unzip. run exe file. choose Uninstall

**Comment by LucasLy** [comment]
> download the release.zip. unzip. run exe file. choose Uninstall

Thank you.
