### ISSUE TITLE
Picture + no A drive

### ISSUE THREAD

**Issue by jack11e** [Metabolix/HackBGRT#107]
I was trying to upload a picture and it said i need an A drive even though there isnt any and when I set teh picture it gets set back to the original one please help

**Comment by chris-thorpe3db** [comment]
In the root directory of the extracted archive, there's a file called "splash.bmp". Overwrite this with the logo you want and run the setup again.

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
