### ISSUE TITLE
Doesn't work on Thinkpad os win10

### ISSUE THREAD

**Issue by GarudaID** [Metabolix/HackBGRT#110]

**Comment by BackMountainDevil** [comment]
try https://github.com/Coxxs/LogoDiy

**Comment by GarudaID** [comment]
[Not Support for my BIOS](https://cdn.discordapp.com/attachments/949340376219668552/1025989196676079636/65.PNG)

**Comment by BackMountainDevil** [comment]
emm I have no other method..

**Comment by GarudaID** [comment]
alrg its ok
