### ISSUE TITLE
Paint isn't lunching  

### ISSUE THREAD

**Issue by i1Zeus** [Metabolix/HackBGRT#114]
## Hi there!! 
apricate the work u have put in it.
I've found an issue where it's will not launch Paint.

#### Lenovo Ideapad 5 pro 16

**Comment by LeBazarDeBryan** [comment]
Try another app like Paint 3D

**Comment by Moonlumen** [comment]
found a fix! start menu > search path > edit sys variables > environment variables and then add %USERPROFILE%\AppData\Local\Microsoft\WindowsApps to PATH
(this makes app aliases work, like the "mspaint" command for the old paint now opening the new [which isn't called mspaint anymore])

**Comment by Metabolix** [comment]
Funny, it still works for me without any extra configuration. But in the next version you will be able to edit the file with any editor before running the setup, so this won't be a problem anymore.

**Comment by Metabolix** [comment]
In version 2.0.0 you can edit the file before installing.
