### ISSUE TITLE
How do i "point" my bootloader to HackBGRT's efi file? Also does this work on bootcamp?

### ISSUE THREAD

**Issue by gitclone93** [Metabolix/HackBGRT#116]
I have a mac pro late 2013 and I have windows and macos on it using UEFI bios and no secure boot. I'm just asking if this works on bootcamp or not. I also need to know how i "point" the mac bootloader to the HackBGRT efi file because i can't figure that out since i only need HackBGRT for windows.

**Comment by Endermanbugzjfc** [comment]
# Beginning
After preparing my dual boot setup, I used [BootOption](https://github.com/bootoption/bootoption) to create a HackBGRT bootloader.
In its config, I pointed the next loader to the EFI file of "Windows Boot Manager".
(The file path can be checked with `bootoption info`.)

I set both the "Boot Camp" and the "Windows Boot Manager" loaders to deactivate by default, hoping HackBGRT can work.
# Attempts (failures)
However, it seems that Boot Camp itself has some mechanisms to always recreate the loaders if any are unavailable. Causing HackBGRT's tweaks to be overridden every time (my guessing):
```
❯ bootoption list         
BootCurrent: Boot0000
BootNext: Not set
Timeout: 5
  2: Boot0001 Windows Boot Manager  *D
 --: Boot0000 Windows Boot Manager
 --: Boot0004 HackBGRT
 --: Boot0080 Boot Camp
 --: Boot0081 Mac OS X
 --: Boot0082 ---------------
```
(`*D` means deactivate by default, notice that there are two "Windows Boot Manager".)
# Observations
I tried Boot X Changer before, which also failed to change the Apple booting logo and resulted in a process circle blocking the screen centre before an operating system finally boots up. Now, it is the same case for HackBGRT, if I arrange its loader to start before any others.
# Environment
Device: **MacBook Air (Early 2015)**
macOS: **Catalina 10.15.7 (19H2)**
Windows: **10 (21H2)**

**Comment by Metabolix** [comment]
I can't provide any support with the Mac boot loader. However, you could try the new release (2.0.0) which can create a proper EFI boot entry. If that doesn't help, you can try some other boot manager for your multi-boot setup.
