### ISSUE TITLE
Logo not showing

### ISSUE THREAD

**Issue by rudra95377** [Metabolix/HackBGRT#118]
i have complated all the steps from setup and it said that it was succsessfully installed but when i restarted my pc it started with normal windows logo

**Comment by ckado** [comment]
Maybe the size of the picture is too large.
There may be other reasons, but I don't know.

**Comment by Pony-John** [comment]
> Maybe the size of the picture is too large.
> There may be other reasons, but I don't know.

Thank you!My problem has been solved.Failed with picture in 4096, succeed with picture in 1600.

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
