### ISSUE TITLE
Pre-compiled Exe for convinience!

### ISSUE THREAD

**Issue by commcad** [Metabolix/HackBGRT#12]
Hi

Thanks for making this available to us. I've recently purchased a WIN10 laptop and it came with a rather annoying (fugly?) OEM boot logo. This NEED changing for something less dramatic, like a butterfly or similar ;)

Glad I've found your tool however my skills aren't polished enough to compile this by myself, wouldn;t know where to begin. Can I kindly ask you to upload a pre-compiled version of your tool (setup.exe) so I can give it a shot please? The image that is the UEFI is named "Splash.jpg" (found out using AMI's ChangeLogo_v5.exe utility).

That'd be awesome and quite helpful. Any other advice RE "how to compile this on Windows/x86" would also be appreciated.

All the best to you!

**Comment by sylveon** [comment]
https://github.com/Metabolix/HackBGRT/releases

**Comment by Metabolix** [comment]
Indeed, the compiled program may be downloaded from [the Releases page](https://github.com/Metabolix/HackBGRT/releases).

**Comment by commcad** [comment]
Sweet, thanks folks. I'll run this as soon as I can make it back home!!!
