### ISSUE TITLE
"EFI System Partition was not found"

### ISSUE THREAD

**Issue by vlad240809** [Metabolix/HackBGRT#120]
Please, can someone help me with this problem?
![image](https://user-images.githubusercontent.com/120692035/207993973-2b425112-12ba-46cc-8068-cc05f08d587e.png)

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version (which also provides a lot more detailed debug output).
