### ISSUE TITLE
HackBGRT doesn't work on HP Pavillion 590

### ISSUE THREAD

**Issue by MCPlayer2015** [Metabolix/HackBGRT#121]
![20230112_205300](https://user-images.githubusercontent.com/56744907/212228031-842f5af9-d963-4d65-8713-396b6ca07900.jpg)

So apparently after reading the messages, it said that it was loading splash.png at one point, but then it decides to load bootmgfw-original.efi.

Why does it do this?

(Also the original boot screen shows the white HP logo while with HackBGRT enabled, it shows the Windows 11 logo instead.)

**Comment by Pony-John** [comment]
My HP laptop shows Windows LOGO,too

**Comment by Pony-John** [comment]
Problem Solved.By changing the size of the picture. Wrong in 4096pt but correct in 1600pt

**Comment by Metabolix** [comment]
The process looks perfectly normal, the latter line is about loading the MS boot loader to actually boot Windows.
