### ISSUE TITLE
How to change boot logo on both Windows and Linux

### ISSUE THREAD

**Issue by Zachary-Muadib** [Metabolix/HackBGRT#123]
I want to use hackbgrt in both Linux and Windows, but how to set hackbgrt so that both systems can modify the boot logo?

**Comment by Metabolix** [comment]
See README. You need to setup HackBGRT as the primary boot loader and use it to load your next boot loader (such as systemd-boot or GRUB). Details depend on your specific situation, so I can't provide any generally working solution.
