### ISSUE TITLE
Failure to show custom logo in Windows 11

### ISSUE THREAD

**Issue by SlickMojang11** [Metabolix/HackBGRT#126]
I wanted to apply a custom image.
it was applied successfully.
but, when i rebooted by laptop to check if it was working.
it resulted to a normal windows 11 logo even though i followed all the requirements for the image.

**Comment by Kaisan10** [comment]
Have you turned off Secure Boot?

**Comment by SlickMojang11** [comment]
> Have you turned off Secure Boot?

I did but it still didn't work.

**Comment by KeeLee2005** [comment]
It works in the resolution of 512px × 297px. It may require a smaller resolution to work. I also tried 1440px × 960px and even 2560px × 1706px, but all failed.
If we want HackBGRT to work the way we want it to, turning down the image resolution is a viable option.

Windows Version: 22631.1900

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
