### ISSUE TITLE
not working on lenevo g580

### ISSUE THREAD

**Issue by alaboratuna** [Metabolix/HackBGRT#127]
hi.

i've seen lenevo logo before i installed hackbgrt, but when i installed hackbgrt i've see windows 11 icon neither the photo I wanted or the lenovo logo.

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot off ?

**Comment by Nofated095** [comment]
me too on Thinpad X250.
Windows 10
before installed i can see the lenovo uefi logo
after installed i could only see the windows origin logo.

sequre boot & csm have turned off

![1A07DD71-8C2F-4065-B323-BB99708F2382](https://github.com/Metabolix/HackBGRT/assets/49985975/78034f5a-6da8-494e-b561-6fc53920357d)

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
