### ISSUE TITLE
Windows can't booting and start flickering at acer logo

### ISSUE THREAD

**Issue by rifqyfano** [Metabolix/HackBGRT#128]
please i need help for the problem, my windows can't booting and start flickering at acer logo. anybody please reply my issues and teach me how to repair it. thank you very much

**Comment by Mac1Chip** [comment]
Not a dev, but this sounds like an EFI bootup issue. Try following the recovery steps in the about page.

**Comment by Metabolix** [comment]
As for the repair (for versions before 2.0), you need to use a Windows installation disk or similar to fix boot issues. After that, please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version (which also provides a lot more detailed debug output).
