### ISSUE TITLE
THANK YOU!!!!

### ISSUE THREAD

**Issue by commcad** [Metabolix/HackBGRT#13]
Amazing stuff, much appreciated for doing this and making it available!

Thanks again :)

**Comment by sylveon** [comment]
Please don't open issues for that. While @Metabolix might appreciate the positive feedback, this sends an email to all watchers and clutters the issue list.

**Comment by Metabolix** [comment]
You're welcome :), but as @sylveon says, let's leave the issue tracker for the more relevant discussion.
