### ISSUE TITLE
Error: Couldn't find required files! Missing

### ISSUE THREAD

**Issue by GlitchyGaming** [Metabolix/HackBGRT#130]
Will Not Work While Install And Says This In Command Prompt
HackBGRT installer version: v1.5.1
EFI System Partition location is A:
Secure Boot is disabled, good!
Error: Couldn't find required files! Missing: C:\Users\Andrew\AppData\Local\Temp\Temp2_HackBGRT-1.5.1.zip\HackBGRT-1.5.1\boot.efi
Press any key to quit.

**Comment by LeBazarDeBryan** [comment]
Try to download it again or try a older version.

**Comment by Metabolix** [comment]
Please try the new release (2.0.0). Extract the zip first, and only then you can start the setup. If you run into problems during installation, please provide `setup.log` file for any further assistance.
