### ISSUE TITLE
Installed HackBGRT, Windows no longer boots.

### ISSUE THREAD

**Issue by zeniq7** [Metabolix/HackBGRT#131]
![image](https://github.com/Metabolix/HackBGRT/assets/136208306/aabb8eaa-a527-481b-9d2d-82d1de8b9898)
Just used a YouTube guide to install BGRT and use a new boot logo, then shut down the system and started it back up. Now, the keyboard and mouse receive no input and I'm stuck at this screen. Not sure where to go from here.

**Comment by LeBazarDeBryan** [comment]
Try to re-install Windows with a USB key and boot to the BIOS by pressing F12 (depend on what pc you have) multiple time.

**Comment by BH-Playz** [comment]
I had this same issue on my laptop!

**Comment by Metabolix** [comment]
I will add a timeout to the "press any key". However, apparently you have enabled debug mode, so the first reasonable step would be to disable that to avoid this "press any key" problem. Also, looks like you have set a weird resolution (1024x1), maybe you should re-check your config.txt.

**Comment by Metabolix** [comment]
Version 2.0.0 has timeout for the key press and won't get stuck like this.
