### ISSUE TITLE
Not Working on Vostro 3750 Modified BIOS

### ISSUE THREAD

**Issue by IIPTI** [Metabolix/HackBGRT#132]
I have a Vostro 3750. After a lot of reseach on BIOS, I flashed a modded bios just to get UEFI. It is UEFI right now but hack bgrt is not working. I wanted UEFI only for Hack BGRT. I used this tool on my friends computers. I loved it. Please tell me a way to make this work on my machine.

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot off?

**Comment by IIPTI** [comment]
Secure boot is not even supported on my laptop.

**Comment by LeBazarDeBryan** [comment]
> Secure boot is not even supported on my laptop.

https://github.com/Metabolix/HackBGRT/issues/129#issuecomment-1551943908

**Comment by IIPTI** [comment]
I think it is a very technical issue,what should I do??

**Comment by LeBazarDeBryan** [comment]
> I think it is a very technical issue,what should I do??

I don't really know, if you can't boot on Windows try re-installing Windows.
If you don't have any problem with Windows try another method to change the boot logo.

Maybe HackBGRT doesn't work because it's a modded BIOS and not the original BIOS.

**Comment by Metabolix** [comment]
Did you also reformat your hard disk to GPT, so that the machine actually boots with UEFI? Did you manage to install HackBGRT or did you get some error message during setup? If you got that far, then you will have to set `debug=1` in the `config.txt` and take a picture of any texts that appear when booting.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen with proper `setup.log` if this is still valid for the most recent version.
