### ISSUE TITLE
Support for Silent installation

### ISSUE THREAD

**Issue by omallasitha** [Metabolix/HackBGRT#133]
I have a custom Windows 10 installation media which has all the bloatware removed, and the most important files getting installed in unattended mode.

While making it, I found that HackBGRT currently does not support silent installation of Boot Logo through command line.

If the developers can include support for silent installation of custom boot logo image in the format of:

c:\HackBGRT\setup.exe my_custom_logo.bmp

or any other format they would introduce us to, would help all small businesses who assemble and sell computers to change default Windows logo to their business logo, as well.

Thank you..

**Comment by BH-Playz** [comment]
I agree! This is needed!

**Comment by Metabolix** [comment]
This is implemented in the next version (coming soon). You will be able to edit config and image beforehand and then install with `setup.exe batch install-[some-extra-choices-here]`.

**Comment by Metabolix** [comment]
Implemented in v2.0.0.
