### ISSUE TITLE
hoi iedereen ik ben mijn oude telefoon aan het upgraden en wil graag tiny 10 erop zetten maar weet niet of en hoe het kan ik heb een samsung a51 heeft iemand er verstand van 

### ISSUE THREAD

**Issue by BramElshout** [Metabolix/HackBGRT#134]
hallo iedereen (nederlands)

ik heb een Samsug a51 die ik wil upgraden.
ik wil graag Tiny 10 er op zetten maar ik kan nog niemand vinden die er verstand van heeft. 
ik zou graag willen weten of het kan met het model dat ik heb en of iemand me ermee kan helpen.

groet Bram Elshout

Hello everyone (English)

i have a samsug a51 i want to upgrade.
I would like to put Tiny 10 on it but I can't find anyone who knows about it yet.
I would like to know if it is possible with the model I have and if someone can help me with it.

Greetings Bram Elshout

**Comment by LeBazarDeBryan** [comment]
Hi! This is a repositorie to change the boot logo on Windows but I can help you.

You can't install Windows 10 but you can emulate it with <a href="https://github.com/limboemu/limbo/releases/latest">Limbo PC Emulator (QEMU)</a> or <a href="https://play.google.com/store/apps/details?id=net.sourceforge.bochs">Bochs</a> (I think).

I can't really help you for the configuration of the applications but there is tutorial on internet.
