### ISSUE TITLE
Not fully compatible with Windows 11 Pro 22H2. Throbber missing on boot screen.

### ISSUE THREAD

**Issue by LovelyLince** [Metabolix/HackBGRT#136]
OS: Windows 11 Pro
Version: 10.0.22621 (22H2)
Build: 22621.1992
Motherboard: B550M PRO-VDH WIFI (MS-7C95)

Installing a custom boot logo causes the throbber on the boot screen to disappear. Uninstalling HackBGRT doesn't fix the issue. HackBGRT used to work perfectly fine until I installed a Windows update about two weeks ago. I don't recall what version of Windows worked fine with HackBGRT.

**Comment by LovelyLince** [comment]
Nevermind. I restarted my PC, & the throbber returned. Note, this was an issue for me on Windows 11 Pro N, but I did tinker with the registry & other settings. So that was probably my fault. After clean installing the normal Windows 11 Pro, I thought HackBGRT was giving me the same issue, but that is not the case so far.

**Comment by LovelyLince** [comment]
The issue has returned. I don't know why. Today, the throbber is just gone.

**Comment by Metabolix** [comment]
HackBGRT doesn't do anything for the Windows boot loader or the throbber. If the problem occurs even after uninstalling HackBGRT, then it is not caused by HackBGRT.
