### ISSUE TITLE
apparently something broke and debug mode isn't verbose enough

### ISSUE THREAD

**Issue by BlockyReduxy0** [Metabolix/HackBGRT#137]
Apparently, as soon as I saw the randomize option, I inserted 50 bmp files and hook them up
But the boot freezes at the manufacturer logo
I can still access the logon and use the computer through bios since I had a backup boot entry
The debug mode ouput a loop of random image replace with weird position of around 3 million x and 0 y (there are still a few 0,0) , then after a while it output "Started bootmgfw, why are we still here" for some moment then restart the cycle, probably because of timeout
Did I broke something? Since it did not output any error?
I can't take any picture since I don't have anything else to take a screenshot with

**Comment by BlockyReduxy0** [comment]
Oh yeah I run windows 11

**Comment by Metabolix** [comment]
Can you upload the config.txt which you created?

**Comment by BlockyReduxy0** [comment]
[config.txt](https://github.com/Metabolix/HackBGRT/files/12269094/config.txt)
this seems to be it

**Comment by Metabolix** [comment]
Looks like you have changed the next boot loader to `boot=\EFI\Microsoft\Boot\bootmgfw.efi`. If you installed HackBGRT with the setup tool (which, as of version 1.5.1, replaces the said file with HackBGRT), you will need to change that line back to `boot=\EFI\HackBGRT\bootmgfw-original.efi`, unless you are using another boot loader (or EFI boot entry) to load HackBGRT directly, in which case you can just "disable" HackBGRT in the setup program.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version (which also provides a lot more detailed debug output).
