### ISSUE TITLE
Found issues on Windows 11

### ISSUE THREAD

**Issue by ibroaobo** [Metabolix/HackBGRT#138]
The following error occurred when running setup.exe and installing in I mode:
**·Error: Couldn't copy new HackBGRT over the MS loader (bootmgfw.efi).
Press any key to quit.**
I need for your help.

**Comment by Metabolix** [comment]
Please try the new release. If you still run into problems during installation, please provide `setup.log` file for any further assistance. If installation succeeds but the image is not changed properly, change the last line in `config.txt` to `debug=1`, reinstall and provide a picture of the debug output shown during boot, along with `setup.log` from the installation.

**Comment by ibroaobo** [comment]
Thanks,I'll try it on October 1st and reply to you that day,thank you for understanding.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
