### ISSUE TITLE
Installed HackBGRT, shows Windows logo instead of custom logo

### ISSUE THREAD

**Issue by GuestTheGamer** [Metabolix/HackBGRT#139]
I have an ASUS Vivobook S551LB with Windows 10. I was able to get it working like 4 months ago but for some reason in August it shows the Windows logo instead of the custom logo. Can somebody fix it?

**Comment by Metabolix** [comment]
Please try the new release. In case of problems, change the last line in `config.txt` to `debug=1`, reinstall and see what happens then. Screen contents and `setup.log` are needed for any further assistance.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
