### ISSUE TITLE
rEFInd + HackBGRT Issue

### ISSUE THREAD

**Issue by IAmOrion** [Metabolix/HackBGRT#14]
Hi There,

I am using rEFInd, which works great, but I also wanted to change the windows boot animation and was so happy when I found your utility!  However, I appear to have a problem.  I have an HP EliteBook 8470p, Secure Boot is OFF in the BIOS, however when rEFInd tries to load the EFI it just gets stuck and stops/freezes.  Nothing happens.  

I can boot windows easy enough as I have a backup entry for the original which works fine, but for some reason this freezes/insta-dies when used alongside rEFInd.

Any thought or ideas?

Many thanks in advance

**Comment by Metabolix** [comment]
Did you follow the Windows instructions or the multi-boot instructions (in the README)?

You should probably use the multi-boot instructions: manually extract (or install and disable) HackBGRT, and then create a custom boot entry in rEFInd with `loader /EFI/HackBGRT/bootx64.efi`.

If that doesn't work, you could install an EFI shell and try running HackBGRT from there to get some more output. Maybe I'll even have to try rEFInd myself...

**Comment by IAmOrion** [comment]
I did the windows setup first.  I have since gone back and tried the multi-boot like you suggest.  It DOES work ... almost.  It Does boot, and it will load windows successfully however no bitmap image is showing.  I have triple checked my config.txt file, I have am using the image that is included in the release download but it doesn't show it.  I just get a black screen followed the normal windows boot animation.  I was hoping this would eliminate that animation and just have a static image instead... or perhaps I've misunderstood and it just shows an Image prior to the normal animation?

**Comment by sylveon** [comment]
Try using a custom image and saving it as a 24-bit bmp in Paint:

![image](https://user-images.githubusercontent.com/6440374/33580958-10dc1776-d91d-11e7-83fd-1e7e90c23fad.png)

You can't eliminate the loading ring, however you can replace the OEM logo.

**Comment by IAmOrion** [comment]
I think perhaps I misunderstood what this EFI Utility did.  I have an HP EliteBook 8470p, and HP already provide an EFI Utility to change the OEM Boot Logo.

I was looking for a way to change to the windows startup animation (in my case the orbs that animate into place).  Obviously it can be done using the "normal" / BIOS install version as winload.exe and winresume.exe and bootres.dll etc are all modded, but I've yet to see an EFI mod to do the same.

I think this means this "issue" isn't an actual issue for me since I misunderstood what it does, so this issue can probably be closed (I'll let you decide) 

Thanks for taking the time to code this and also to respond.

Regards

**Comment by Metabolix** [comment]
It's true that only the OEM logo (vendor logo) will be changed, and any Windows animations will not be changed. So apparently this doesn't help in your use case. (Also, nice to know that HP already supports changing the image...)

However, if you previously saw the OEM logo (in your case, HP logo) during boot and if HackBGRT only removes that but fails to insert the new logo, that's clearly some kind of bug and would require closer inspection of the ACPI tables before and after running HackBGRT. If you can add `debug=1` in the config and inspect the output, it might be helpful. (See http://i.imgur.com/fXoYqQ0.gifv for a sample output which helped me solve issue #1.) Also, dumping the old BGRT (possible from `/sys/firmware/efi/efivars/` IIRC) might be helpful, preferably both with and without HackBGRT.

**Comment by sylveon** [comment]
If HackBGRT successfully removed the older BGRT, shouldn't we see the
Windows logo instead of just a black screen with spinners?

Also, it's nice of HP to have a tool to change the logo in the firmware.
Mind sharing it with me, I'm curious to see if it works on my HP Pavilion.
It probably won't work because it isn't a business laptop but it can't hurt
to try.

**Comment by Metabolix** [comment]
I suppose "orbs that animate into place" means something like the [Windows 7 animation](https://www.youtube.com/watch?v=A2ZL2vnf-Uw), which is of course more than a simple image and probably not in the scope of HackBGRT at all.
