### ISSUE TITLE
Video example of the result

### ISSUE THREAD

**Issue by josephernest** [Metabolix/HackBGRT#140]
Hi, 

Congrats for making HackBGRT available!

Would someone have a video showing the boot sequence after using HackBGRT?

It could be super useful for anyone who wants to use this tool (and modify UEFI settings), to be sure it is what we are looking for.

A boot sequence is often composed of ~ 10 different screens (BIOS POST, BIOS logo, [Windows pre-login screen](https://i.stack.imgur.com/iLRVH.png), etc.), so it would be interesting to see exactly which one of these screens HackBGRT is able to modify.

@Metabolix maybe? Thanks a lot in advance!

**Comment by ryanrudolfoba** [comment]
Maybe this is what you are looking for i just crrated a video of it on my Windows Handheld PC.

https://youtu.be/oijGgcfeD1k

Take note that the install process on that video is different - i repackaged it and just created simple batch files for the install / uninstall.

**Comment by josephernest** [comment]
Thank you for your answer @Metabolix.

More precisely, which one of these screens can HackBGRT change?

Screen A:

[![enter image description here][2]][2]

Screen B:

[![enter image description here][3]][3]

Screen C:

[![enter image description here][4]][4]

Screen D:

[![enter image description here][5]][5]


  [2]: https://i.stack.imgur.com/jT48c.jpg
  [3]: https://i.stack.imgur.com/STU7T.jpg
  [4]: https://i.stack.imgur.com/SY9rq.jpg
  [5]: https://i.stack.imgur.com/nTIMf.jpg

**Comment by ryanrudolfoba** [comment]
screen C

**Comment by josephernest** [comment]
Screen C can already be removed with:

    bcdedit /set quietboot on
    bcdedit /set bootux Disabled
    bcdedit /set bootuxdisabled on

Do you know how to just remove Screen B without having to modify UEFI / without using HackBGRT?

**Comment by Metabolix** [comment]
HackBGRT does not draw anything, it just gives Windows boot loader an alternative image to draw. Obviously it's not possible to change the screen contents before the boot process without modifying the UEFI firmware somehow.
