### ISSUE TITLE
Support for ARM (32-bit)

### ISSUE THREAD

**Issue by Metabolix** [Metabolix/HackBGRT#142]
Support for ARM (32-bit)

**Comment by sylveon** [comment]
Windows itself no longer supports ARM32, so not sure how much worth the effort is, easier to focus on ARM64.

Additionally, the Surface RT doesn't have the means to disable Secure Boot IIRC.

**Comment by Metabolix** [comment]
The git version can be compiled for ARM 32-bit. No shim-signed, though. I won't provide any support for installation, as it possibly requires expert knowledge / tailored tutorial for the specific device. Some information seems to be available at https://openrt.gitbook.io/open-surfacert/common/boot-sequence/uefi/secure-boot.
