### ISSUE TITLE
are there any size restrictions for the bmp ? 

### ISSUE THREAD

**Issue by Ulf3000** [Metabolix/HackBGRT#143]
what the title says .. what is the maximum resolution for the image ?

**Comment by Metabolix** [comment]
It can be as big as your screen resolution. Note that sometimes the resolution is smaller during boot (e.g. only 1024x768) and you need to adjust the image accordingly.

**Comment by Metabolix** [comment]
My tool tries to select the maximum resolution available during boot. Nice to hear it manages to be better than default Windows setting. 😊

**Comment by Ulf3000** [comment]
yeah looks great , ive now tried to install multiple images (the same image but with different colorscheme) 
![splash7](https://github.com/Metabolix/HackBGRT/assets/10765339/48e613f5-8a01-4d40-9aff-ed9a1e625929)

so nice , thanx a ton for this  !

ill close now :)
