### ISSUE TITLE
wont work with fujitsu motherboard

### ISSUE THREAD

**Issue by alelelal24** [Metabolix/HackBGRT#145]
shows motherboard logo and then windows logo. it wont show the logo i wanted
i have gpt and this is uefi 
![balls](https://github.com/Metabolix/HackBGRT/assets/116514488/03c2b75b-89e6-402c-a04c-ab8014392c1d)

**Comment by Metabolix** [comment]
Make sure that your picture is not bigger than the screen (1920x1080).

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
