### ISSUE TITLE
 How to compile it myself 

### ISSUE THREAD

**Issue by starzc-galaxy** [Metabolix/HackBGRT#146]
apt-get install gnu-efi

src/config.h:3:10: fatal error: efi.h: 没有那个文件或目录

    3 | #include <efi.h>

      |          ^~~~~~~

compilation terminated.

where is efi.h file

**Comment by Metabolix** [comment]
It uses a mingw cross compiler. You need to build gnu-efi with the cross compiler too.

**Comment by Metabolix** [comment]
Now it compiles with Clang, feel free to try the newest git version.
