### ISSUE TITLE
it doesnt work with legacy bios

### ISSUE THREAD

**Issue by PingviniB** [Metabolix/HackBGRT#148]
it says efi system partition was not found (legacy bios)

**Comment by My1** [comment]
https://github.com/Metabolix/HackBGRT#usage

> Make sure that your computer is booting with UEFI.

**Comment by PingviniB** [comment]
so it only works with uefi?

**Comment by Metabolix** [comment]
Indeed. The boot process is totally different. There were already solutions for legacy BIOS when I started this project, it's not interesting, and legacy BIOS is dying anyway.
