### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Elliot60501** [Metabolix/HackBGRT#15]
When I saw this program I perked up and tried to use it, but when I started the setup.exe, it gave me this message: "Press enter to exit, or give ESP path here". Do you know what I mean? I'm probably being a idiot and I need to read the README file, but it is in a format that I don't know how to open up.

**Comment by Sam1370** [comment]
The readme file is a .txt

**Comment by Sam1370** [comment]
Just add .txt to the end of it

**Comment by Sam1370** [comment]
If you have notepad++ then right click and click edit with notepad++

**Comment by Metabolix** [comment]
You can see README.md online here: https://github.com/Metabolix/HackBGRT/blob/master/README.md
