### ISSUE TITLE
I think This location needs a FreePool(bmp) . When BMP structure is invalid . 

### ISSUE THREAD

**Issue by FREEWING-JP** [Metabolix/HackBGRT#152]
I think This location needs a FreePool(bmp) . When BMP structure is invalid . 

https://github.com/Metabolix/HackBGRT/blob/da9909bbdd00d39089c804af95e5d0976835f7f7/src/main.c#L248-L254

as below
```
		}
		FreePool(bmp);  <<< Add This
		Print(L"HackBGRT: Invalid BMP (%s)!\n", path);
	} else {
```

**Comment by Metabolix** [comment]
Fixed in version 2.2.0, although the memory is probably freed anyways at some point during boot.
