### ISSUE TITLE
Unhandled exception 

### ISSUE THREAD

**Issue by imomobile** [Metabolix/HackBGRT#155]
![IMG_20231030_171956922_HDR~2](https://github.com/Metabolix/HackBGRT/assets/86445660/1d5a120c-e3e2-4a65-87be-5bd065c32d50)
Trying to run this program gives me this error.
Specs:
I don't know if secure boot is enabled (no option in BIOS, but this is a 2010 laptop)
UEFI
Windows 8.1 x64
4GB RAM
Intel core i5 540M
Dell latitude e6410

**Comment by Metabolix** [comment]
The current installer supports only recent Windows (and .NET) versions. Support for old versions is not planned and will not be actively maintained.

**Comment by Metabolix** [comment]
Apparently Win 8.1 is still supported so you can upgrade .Net Framework with either Windows Update or directly from https://dotnet.microsoft.com/en-us/download/dotnet-framework.
