### ISSUE TITLE
HackBGRT

### ISSUE THREAD

**Issue by Alexlnnz** [Metabolix/HackBGRT#156]
Bonjour j'ai un souci avec hackBGRT,  j'utilise un HP probook 440 G9, le souci c'est que quand je démarre mon pc, il me dit que l'image n'est pas valide. Donc j'aimerai désinstaller hackBGRT mais je ne trouve pas les fichiers nécessaires à sa désinstallation. Je n'ai pas accès à mon BIOS.
En attente de votre aide.

**Comment by Metabolix** [comment]
Avez-vous désactivé SecureBoot ou non ?  Pour le moment, il n'est pas possible d'utiliser HackBGRT avec SecureBoot.

Vous pouvez utiliser le même setup.exe pour désinstaller.

**Comment by Metabolix** [comment]
La nouvelle version 2.2.0 peut être installée avec Secure Boot activé, veuillez le tester. Pour éviter les problèmes, n'utilisez pas la méthode d'installation Legacy.
