### ISSUE TITLE
Two logos appear - manufacturer logo first followed by custom logo - expected behaviour?

### ISSUE THREAD

**Issue by megamaniac** [Metabolix/HackBGRT#158]
Hi,

Just wanted to check this is expected behaviour, I just ran HackBGRT (I tried all three options, with the same result) and it did change the logo that appears above the spinning loading symbol - i.e. a replacement for the Windows Logo. 

The 'BIOS' logo from the manufacturer appears before this... am I right to assume this is nothing to do with the BGRT and can't be overcome?

**Comment by sylveon** [comment]
Correct

**Comment by megamaniac** [comment]
Ok thanks, makes sense. Appreciate your work and it's nice to be able to modify the Windows logo at least!

**Comment by megamaniac** [comment]
I'll close this.
