### ISSUE TITLE
Installatio has no effect

### ISSUE THREAD

**Issue by chocochaos** [Metabolix/HackBGRT#16]
I am trying to change my boot image using HackBGRT, but I'm having no luck so far.

- If it matters, I have extracted HackBGRT to C:\Users\me\Downloads\HackBGRT-1.5.0
- I have tried with both the default config file, and with `boot=\EFI\Microsoft\Boot\bootmgfw.efi` (the readme and the comment in `config.txt` contradict each other. The config file says I should point it to the real windows bootloader, the readme tells me I need not change the config file at all. So I tried both methods.
- Other than that I have made no changes whatsoever, I did not even edit the provided image.

After running `setup.exe`, I get the message `HackBGRT is now installed.` However, when restarting I still see my device manufacturer's logo, not the one from HackBGRT. If I mount my EFI partition, I do see a HackBGRT directory. When running bcdedit, I get the following information:

	Windows Boot Manager
	--------------------
	identifier              {bootmgr}
	device                  partition=Z:
	path                    \EFI\Microsoft\Boot\bootmgfw.efi
	description             Windows Boot Manager
	locale                  en-GB
	inherit                 {globalsettings}
	default                 {current}
	resumeobject            {2b73de1b-dd0a-11e6-bac7-be6c3a5b302e}
	displayorder            {current}
	toolsdisplayorder       {memdiag}
	timeout                 3

	Windows Boot Loader
	-------------------
	identifier              {current}
	device                  partition=C:
	path                    \WINDOWS\system32\winload.efi
	description             Windows 10
	locale                  en-GB
	inherit                 {bootloadersettings}
	recoverysequence        {2b73de1d-dd0a-11e6-bac7-be6c3a5b302e}
	displaymessageoverride  Recovery
	recoveryenabled         Yes
	isolatedcontext         Yes
	allowedinmemorysettings 0x15000075
	osdevice                partition=C:
	systemroot              \WINDOWS
	resumeobject            {2b73de1b-dd0a-11e6-bac7-be6c3a5b302e}
	nx                      OptIn
	bootmenupolicy          Standard
	quietboot               Yes
	sos                     Yes

**Comment by Metabolix** [comment]
It's possible (although weird) that your computer uses another copy of the Windows boot loader on another partition, in which case HackBGRT would not get loaded at all. What is that Z: in bcdedit output?

You could also install another boot loader (like GRUB or systemd-boot) and then use the multi-boot instructions in README for installing HackBGRT. That's very reliable but needs the extra effort of another bootloader.
