### ISSUE TITLE
Setup.exe error (not working cmd)

### ISSUE THREAD

**Issue by ehtiSham-0** [Metabolix/HackBGRT#164]
As shown in image setup.exe stops working upon opening with run as administrator (same error on latest version also)

Help to run the cmd and change logo
![IMG20231209193108](https://github.com/Metabolix/HackBGRT/assets/150510971/22596fff-e9a1-4df0-826f-cfe8c96e1c64)

**Comment by userdev265scratchandpython** [comment]
that's an issue i can't fix ;-;

**Comment by Metabolix** [comment]
You have too old .Net Framework. You need version 4.8 to run this installer. Use Windows Update or update manually from https://dotnet.microsoft.com/en-us/download/dotnet-framework. I will add a better error message in next release.

**Comment by userdev265scratchandpython** [comment]
i have the latest vertion and it's just buggy

**Comment by userdev265scratchandpython** [comment]
on my pc ;-;

**Comment by Metabolix** [comment]
If you think you get this error with newest .Net Framework, then please include the information about how you installed it, what is the version number and what did you do to start this program. It's obvious that this particular error (about a missing method) does not happen with .Net Framework 4.8 or newer which contain that method.

**Comment by Metabolix** [comment]
You may try the newest version (v2.4.0) in which I replaced that particular Prepend method call with another method, so that an older .Net version could work. However, I still don't actively support old .Net versions, so if it's still not working, feel free to fix it and send a pull request.
