### ISSUE TITLE
anyway to have grub use the shim loader for my windows boot manager entry?

### ISSUE THREAD

**Issue by FanACYT** [Metabolix/HackBGRT#165]
is there any way to have grub use the shim loader for my windows boot manager entry instead of the normal microsoft one on my linux dual boot

**Comment by Metabolix** [comment]
As far as HackBGRT is concerned, you can select the option to install only files (without creating a new boot entry). This installs shim as `/EFI/HackBGRT/loader.efi` and HackBGRT as `/EFI/HackBGRT/grubx64.efi`.

Then you should be able to chainload with GRUB2 like this:

```
menuentry "Windows with HackBGRT" {
        insmod part_gpt
        insmod chain
        set root='(hd0,gpt1)'
        chainloader /EFI/HackBGRT/loader.efi
}
```

Refer to GRUB and/or your OS documentation for further instructions.
