### ISSUE TITLE
cannot change logo

### ISSUE THREAD

**Issue by userdev265scratchandpython** [Metabolix/HackBGRT#166]
windows 11 always keeps it's logo,not changing at all,can you help me out?

**Comment by Metabolix** [comment]
You failed to include the log file.

Does it work if you first install with option `J` and then with option `I`?

**Comment by userdev265scratchandpython** [comment]
tested(i'm on real hardware with 2 windows installed) and the log file is empty(it had errors with my pc's motherboard ig)

**Comment by Metabolix** [comment]
The very first line which this program prints is also written in the log. So if the log is empty, then you have not run the setup properly.

**Comment by Metabolix** [comment]
Please test with the newest version and attach the log in case of problems.

**Comment by Metabolix** [comment]
No answer, no details, closing.
