### ISSUE TITLE
Only can change the windows uefi book logo,but the first vender logo can't change. 

### ISSUE THREAD

**Issue by Xiantao-Qiu** [Metabolix/HackBGRT#167]
**What happens?**
Only can change the windows uefi book logo,but the first vender logo can't change. .

**How this happens?**
[setup.log](https://github.com/Metabolix/HackBGRT/files/13693873/setup.log)

1st time:
      1,setup
      2,I

2nd time (after complete remove):
      1,setup
      2,J
      3,reboot 
      4,I

The current state is that the contact logo is displayed first after starting the computer, then the customized logo is displayed with a spinning circle indicating that the startup is in progress.

**Comment by My1** [comment]
This has been asked often enough, this is normal. hackbgrt only changes the
logo in windows's Bootloader, the image shown during POST from the
mainboard is not that easy to change.
