### ISSUE TITLE
Secure boot question

### ISSUE THREAD

**Issue by liakify** [Metabolix/HackBGRT#17]
I managed to get this program enabled and working, and for me I just want to remove the OEM logo and use the default windows logo (in config I used image=remove). 

But if my understanding is correct, does it mean I must always have secure boot off all the time? Can I switch secure boot on at all? I have my stuff backed up but I still don't want to risk having to go through the whole restoration process if I can't boot windows.
I just don't feel comfortable to have secure boot off all the time for the sake of a logo; I'll probably live with the ugly OEM logo if this isn't possible...

Thanks in advance

**Comment by sylveon** [comment]
You can add Secure Boot support as I did by adding your own keys in the Secure Boot database and signing the efi file with them. Some machines have a simple option to register a certificate in the db, in that case it's fairly easy and fail-proof to do.

Some like mine didn't. In that case, the process is fairly complicated, not really documented, and can fuck up your machine if you fail. But in the end I did succeed, and now I can boot Arch Linux and HackBGRT while keeping Secure Boot on.

Here's a few resources that helped me in the process of owning my Secure Boot keys (those are instructions for a Linux distro, but a live CD will work **as long as you backup all keys you generate somewhere super-safe**):

 - https://blog.hansenpartnership.com/owning-your-windows-8-uefi-platform/
 - http://jk.ozlabs.org/docs/sbkeysync-maintaing-uefi-key-databases/
 - http://www.rodsbooks.com/efi-bootloaders/controlling-sb.html (Note here that some firmwares will delete all the keys before enabling Setup Mode, so if you follow this guide, make sure to restore the KEK, DB and DBX backups the guide tells you to do before adding your stuff.)

Good luck. Google is your friend.

As for signing, just use sbsign like this (again from within Linux):
```
sbsign --key myHackBGRTcert.key --cert myHackBGRTcert.crt --output hackbgrt-signed.efi /boot/wherever-hackbgrt-efi-file-is`
```
and put hackbgrt-signed.efi over the original HackBGRT EFI file.

**Comment by gadgethm** [comment]
I'm currently running HackBGRT alongside rEFInd (which is a bootloader made by the same guy in that third link above: http://www.rodsbooks.com/refind/).  He has an entire section on how to use the tool with secure boot to run any efi program with secureboot enabled.  As sylveon said, the best way is to simply sign the binary yourself, though there are several ways different ways to enroll its hash into the whitelist secureboot uses.  If you have trouble figuring it out on your own, feel free to message me directly and I can walk you through my personal setup in more detail.

**Comment by Metabolix** [comment]
Thanks to @sylveon for a very good answer.
