### ISSUE TITLE
Bug/suggestion

### ISSUE THREAD

**Issue by arukateru** [Metabolix/HackBGRT#170]
When I was in my EFI partition I noticed this file in the HackBGRT folder. I translated it and it means "bad". I doubt this is intentional...I imagine it's just some random characters being interpreted as unicode... and this is all just a coincidence. I would imagine it is a randomly generated file or something, or perhaps I have a problem with my filesystem. I found it was just one of the efi-signed applications. Still, could definitely scare some users into thinking this is malware.

![image](https://github.com/Metabolix/HackBGRT/assets/84914212/27b4449f-192a-4ac2-ae73-7cdce6079be2)

**Comment by Metabolix** [comment]
Thanks for the translation, I hadn't checked that. You are correct in that the file name is some data interpreted as UCS-2. However, the file is unfortunately needed to avoid certain errors, as explained in commit a44b929.
