### ISSUE TITLE
Can you use this script if your drive is encrypted with VeraCrypt?

### ISSUE THREAD

**Issue by ambroziewiczdaniel** [Metabolix/HackBGRT#172]
As in the title, can I use it while my system partition is encrypted with VeraCrypt? I know that I the risk is always there, however are there any determinate problems with that?

**Comment by Metabolix** [comment]
It should be ok.

I checked [VeraCrypt BootEncryption.cpp](https://github.com/veracrypt/VeraCrypt/blob/VeraCrypt_1.26.7/src/Common/BootEncryption.cpp) and it looks like they just replace the MS loader (`bootmgfw.efi`) with VeraCrypt, so HackBGRT should work just fine.

If HackBGRT says "MS boot loader not found", you may need to install from command-line with `setup.exe batch install allow-bad-loader enable-entry`.

Give it a try and tell everyone if it works. :)

**Comment by ambroziewiczdaniel** [comment]
I've tried and it worked when I applied the steps from readme.md. The image doesn't appear on the login page, however it shows up after entering the password.
Thank you!
