### ISSUE TITLE
"EFI System Partition was not found" on Windows Server 2012 Build 8250

### ISSUE THREAD

**Issue by JadenNeil2020** [Metabolix/HackBGRT#175]
I tried to make a custom boot image on My Windows Server 2012 Build 8250
but this happens:

<img width="175" alt="image" src="https://github.com/Metabolix/HackBGRT/assets/75154286/6d3b1e81-b5a0-4991-9eb2-f8dc2df16507">

I have the EFI System Partition on Disk 1. How do I fix it?

Thanks!

**Comment by JadenNeil2020** [comment]
Please note that I'm using the latest version 2.4.0. So Alright

**Comment by Metabolix** [comment]
`setup.log`, please.

**Comment by JadenNeil2020** [comment]
oh i forgot

**Comment by JadenNeil2020** [comment]
> `setup.log`, please.

Unfortunately, I cannot send the log to the real pc to you because I'm using a VirtualBox

**Comment by Metabolix** [comment]
Transferring files should be pretty basic stuff with virtual machines. But in any case, Windows Server 2012 is already EOL, and Windows Server in general is not an interesting use case for this software (why do you care about boot logo in a server environment?), so I'm not going to do anything about this.
