### ISSUE TITLE
Is it possible to use this suppress the windows welcome UI sign in animation?

### ISSUE THREAD

**Issue by jazir555** [Metabolix/HackBGRT#176]
I want Windows to show zero UI elements until the default shell boots. A completely black screen. Is that possible with this project? If not, could you be able to add that functionality?

**Comment by Metabolix** [comment]
This tool only changes the logo (which can be a black image, if you wish). It does not modify the Windows boot loader in any way. By design, it is impossible change anything in the boot process with this tool.
