### ISSUE TITLE
Incorrect Resolution on Boot and Logo Not Seeing

### ISSUE THREAD

**Issue by Buhose22** [Metabolix/HackBGRT#177]
**What happens?**
Describe the bug.
Cannot Load /EFI/HackBGRT/S?
Falling Back to Default Loader

**How this happens?**
Explain exactly the steps you did:
1. Install HackBGRT into Windows
2. Reboot the Computer
3. EFI Load Error

![Example Image](https://github.com/Metabolix/HackBGRT/assets/113225306/715e5e9b-068e-4835-b218-0c5526cd70d6)

**Comment by Metabolix** [comment]
setup.log is required for any assistance.

**Comment by Metabolix** [comment]
No reply. Cannot help. Please double-check that you are using the most recent installer (version 2.4.0 as of March 2024). If the problem still occurs, reopen the report with a proper log file.
