### ISSUE TITLE
where setup.exe

### ISSUE THREAD

**Issue by Username-is-not-taken-lololol** [Metabolix/HackBGRT#179]
**What happens?**
  There is not setup.exe.

**How this happens?**
1. Download HackBGRT-(version).zip and extract all files.
2. And no setup.exe

**Log file**
there is no setup.exe

![image](https://github.com/Metabolix/HackBGRT/assets/111068836/a1ada3ae-6086-4be5-bb25-377f360b0429)

**Comment by Metabolix** [comment]
You have downloaded the source code and not the release. Go to the releases page to download the release.
