### ISSUE TITLE
Secureboot on Windows in other toturial 

### ISSUE THREAD

**Issue by vlldk** [Metabolix/HackBGRT#18]
On Windows, what is the difference between this method and [this](https://www.youtube.com/watch?v=BfNw5cKY6qI)? I think the YouTube tutorial works with secure boot whereas this needs extra work - can't a fully automated method be implemented?

**Comment by sylveon** [comment]
You linked the wrong video.

The method of changing a DLL doesn't overrides the OEM logo, where HackBGRT can. It's not possible to automate secure boot disabling or key enrollment, as Microsoft makes it explicit in their Windows licensing terms that it must not be possible to do inside the OS (and it's a good thing, imagine the number of rootkits that would love to be able to disable Secure Boot from within the OS)

**Comment by vlldk** [comment]
[Link fixed](https://www.youtube.com/watch?v=BfNw5cKY6qI)
Ok, so just to be sure - if i have a Dell logo on boot the DLL change won't change the boot logo? 

And how would i get it to work with secure-boot? And with that, how great is the risk and breaking something?

**Comment by sylveon** [comment]
You're right, changing the DLL won't change the Dell logo.

For secure boot, see #17
