### ISSUE TITLE
Hack BGRT and GPT partition scheme on disk/

### ISSUE THREAD

**Issue by tapochek666** [Metabolix/HackBGRT#184]
For some reason, it is not written anywhere that it does not work if the disk has a GPT partition scheme!? When you boot Windows 11 from a GPT disk, instead of the Windows logo, the motherboard logo appears. Even without Hack BGRT, even with Hack BGRT.

**Comment by Metabolix** [comment]
It absolutely works with GPT and only GPT (since Windows doesn't support UEFI with MBR). If you have a problem, check the log. If you need help, post the log.

**Comment by tapochek666** [comment]
Here are 2 logs after installation on “I” and “J” + screenshots of what I now have on the efi partition.
[logs.zip](https://github.com/Metabolix/HackBGRT/files/14937270/logs.zip)

**Comment by Metabolix** [comment]
Looks like your computer resets the BootOrder (= skips HackBGRT and boots Windows directly). I don't know why this still happens for some people. After installing and rebooting, you can enter UEFI Setup (so-called BIOS) and manually set HackBGRT as the first boot option.

**Comment by tapochek666** [comment]
In the boot partition of my UEFI (BIOS), Windows Boot Manager is in first place, my ssd with the installed OS and efi partition is in second place, and USB is in third place. HackBGRT is not listed. Just for fun, I swapped Windows Boot Manager and SSD - to no avail. In the Boot Menu (F 12) this way or that way - in the first place is the Windows Boot Manager (SSD model), in the second place is USB and nothing else.

**Comment by tapochek666** [comment]
In the boot partition of my UEFI (BIOS), Windows Boot Manager is in first
place, my ssd with the installed OS and efi partition is in second place,
and USB is in third place. HackBGRT is not listed. Just for fun, I swapped
Windows Boot Manager and SSD - to no avail. In the Boot Menu (F 12) this
way or that way - in the first place is the Windows Boot Manager (SSD
model), in the second place is USB and nothing else.

чт, 11 апр. 2024 г. в 20:04, Lauri Kenttä ***@***.***>:

**Comment by Metabolix** [comment]
The setup log clearly shows that HackBGRT is added to NVRAM boot entries (unless you already uninstalled it?), so if it's still not visible in your boot menu, there's a problem with your firmware. Nothing more that I can do, sorry.

**Comment by tapochek666** [comment]
Ok, thanks for the clarification.

чт, 11 апр. 2024 г. в 21:48, Lauri Kenttä ***@***.***>:
