### ISSUE TITLE
Windows 11 not showing custom image

### ISSUE THREAD

**Issue by trwy7** [Metabolix/HackBGRT#186]
**What happens?**
Describe the bug.
HackBGRT says it has displayed the image, however it has not, and windows shows the default image on boot, not even the OEM logo.

**How this happens?**
Explain exactly the steps you did:
1. Download HackBGRT-2.4.1.zip and extract all files.
2. Start setup.
3. Select install
4. Modify config.txt to use asus.bmp instead of splash.bmp
5. Reboot
6. Windows shows windows 11 logo, and not custom

**Log file**

[setup.log](https://github.com/Metabolix/HackBGRT/files/14948242/setup.log)

*This does happen when booting without refind*

**Comment by Metabolix** [comment]
Your log doesn't include the installation. Does it work with the default image? Did you copy `asus.bmp` manually or with the installer? When copying manually, make sure that the image format is exactly right.

**Comment by trwy7** [comment]
> Your log doesn't include the installation. Does it work with the default image? Did you copy `asus.bmp` manually or with the installer? When copying manually, make sure that the image format is exactly right. (Note that HackBGRT only reads the file, Windows shows it and so the BMP format requirements come from Windows.)

Thank you, I wonder why I didnt think of this.
