### ISSUE TITLE
Error: Failed to install image splash.bmp to A:\EFI\HackBGRT\splash.bmp. 

### ISSUE THREAD

**Issue by ViewerDnB** [Metabolix/HackBGRT#189]
this is what i got everytime i try 
idk if it is bcs i have opencore (windows and macOS boot) 
if anybody does know how i can setup it will be amazing sorry if i post in bug report, im quite noob on github

This setup program lets you edit just one image.
Edit config.txt manually for advanced configuration.
Draw or copy your preferred image to splash.bmp.

EFI System Partition location is A:\
Detected arch=x64 from MS boot loader, the installer will use that.
Windows was booted at 06/05/2024 01:09:35 p. m.. Remember to reboot after installing!
You may have to disable Fast Startup (Hiberboot) to reboot properly.
Completed action 'disable-overwrite' successfully.
Installed config.txt to A:\EFI\HackBGRT\config.txt.

Error: Failed to install image splash.bmp to A:\EFI\HackBGRT\splash.bmp.
If you need to report a bug,
 - run this setup again with menu option L (show-boot-log)
 - then include the setup.log file with your report.
Press any key to quit.

**Comment by Metabolix** [comment]
You didn't include setup.log so there's really not much information in your report. But at least check that you didn't remove or rename splash.bmp, and check that your boot partition is not full. (Open command prompt as administrator and type `mountvol a: /s` to mount the boot partition, then check the free space from My computer.) If it's full, then you cannot install (at least not a big image), unless you manage to remove some unused files there.

**Comment by Metabolix** [comment]
No reply, closing. Maybe I'll add a check to see if the disk partition is full, to give a better report in that case (which is one of the few possible problems with copying).
