### ISSUE TITLE
bitlocker triggers when removed

### ISSUE THREAD

**Issue by PLGGitHub1** [Metabolix/HackBGRT#191]
**What happens?**
i tried removing it  and still bitlocker triggers

**How this happens?**
Explain exactly the steps you did:
1. Download HackBGRT-(version).zip and extract all files.
2. Start setup.
3. Select reboot
4. done!11!!11111!!!1111!!1!!

**Log file**
removed app already
cant show

**Comment by My1** [comment]
bitlocker recovery stuff triggers on every bigger change to the boot chain at least once. sometimes it might after restoring to pause and unpause bitlocker in case that happens

**Comment by Metabolix** [comment]
>     3. Select reboot

Obviously "reboot" is not "remove".

>     4. done!11!!11111!!!1111!!1!!

I'm not going to take this kind of report seriously.

> **Log file** removed app already cant show

You can always download it again and run it again. No log, no help.

**Comment by PLGGitHub1** [comment]
> > 3. Select reboot
> 
> Obviously "reboot" is not "remove".
> 
> > 4. done!11!!11111!!!1111!!1!!
> 
> I'm not going to take this kind of report seriously.
> 
> > **Log file** removed app already cant show
> 
> You can always download it again and run it again. No log, no help

 you will never live

**Comment by Metabolix** [comment]
> you will never live

Wtf?
