### ISSUE TITLE
Ox1a verification failed error

### ISSUE THREAD

**Issue by oldroblox** [Metabolix/HackBGRT#193]
When I tried to boot windows it gave me the error 0x1a verification failed error i tried resetting me PC still won't work

**Comment by Metabolix** [comment]
This is expected and explained in the instructions. There's a file named README which you should definitely read. It tells you to read [shim.md](https://github.com/Metabolix/HackBGRT/blob/main/shim.md) as well.

**Comment by oldroblox** [comment]
Sorry but i fix the problem i had to restore my pc to factory settings

**Comment by oldroblox** [comment]
The problem has been resolved by the dev of the program
