### ISSUE TITLE
Custom Name Call for HackBGRT

### ISSUE THREAD

**Issue by WizZassa** [Metabolix/HackBGRT#194]
hey guys, maybe I'm posting twice or incorrectly, but I haven't been able to find anything about it in the closed topics.
I apologize in advance

So far I've always written a mod for the BIOS (mostly Insyde20) that changes the logo. However, this is too time-consuming for me. HackBGRT has worked perfectly for me so far on every device, is reliable and doesn't cause any problems and it's much quicker to change the logo above, even if the manufacturer is still visible for a short time.

What bothers me is that the boot option is "HackBGRT", which confuses a lot of my people because the word "Hack" appears in it.
That's why I wanted to ask whether it's possible to adjust this independently in the config or something similar. 

The same also applies to the path that is stored (optional)
for example, instead of "EFI\HackBGRT\...." to "EFI\Wizard\...."

I have already tried to change the config a little in this regard, but this causes a crash, freezes or it simply doesn't work

**Comment by Metabolix** [comment]
It is open source software, so go ahead, change it and build it. There will never be an option to choose a path or a name. But who knows, maybe some day I might rebrand it, now that it's a bit safer to use.

**Comment by sylveon** [comment]
You can manually install and register the file wherever you want with whatever name you want.

**Comment by Metabolix** [comment]
Just in case, with v2.5.2 the EFI app is no longer restricted to \EFI\HackBGRT but can be manually installed in a different directory.
