### ISSUE TITLE
Verifiying shim SBAT data failed, SBAT self-check failed

### ISSUE THREAD

**Issue by Bjk8kds** [Metabolix/HackBGRT#197]
I have successfully installed HackBGRT before using the steps in shim.md, however after the Windows 11 update in August 2024 (KB5041585) windows fails to boot at all and only displays a warning like this:

> Verifiying shim SBAT data failed: Security Policy Violation
> Something has gone seriously wrong: SBAT self-check failed: Security Policy Violation

This can be resolved by disabling Secure Boot and/or uninstalling HackBGRT.
Is there a way to install HackBGRT with Secure Boot enabled?
![IMG_20240814_175147](https://github.com/user-attachments/assets/b62b9f97-0c3c-41cf-8111-898c1bc9446c)

**Comment by MKKelvinHK** [comment]
I also having this issues after got update of Windows 11.

**Comment by Metabolix** [comment]
Maybe they now require shim 15.8. I'll update the files in shim-signed from [Debian repo](https://packages.debian.org/sid/shim-signed) when I have the time. Nice if someone could test it. You need to get the new shimx64.efi and mmx64.efi, then reinstall.

**Comment by Metabolix** [comment]
Can you try this version: [HackBGRT-2.5.0-3-gc9c5c9b.zip](https://github.com/user-attachments/files/16638810/HackBGRT-2.5.0-3-gc9c5c9b.zip) (actually you only need to copy shim-signed from this). It has a newer version (15.8) of the shim boot loader.

**Comment by Skulldorom** [comment]
> Indeed, KB5041585 info page says: "This update applies SBAT to systems that run Windows. This stops vulnerable Linux EFI (Shim bootloaders) from running."
> 
> Can you try this version: [HackBGRT-2.5.0-3-gc9c5c9b.zip](https://github.com/user-attachments/files/16638810/HackBGRT-2.5.0-3-gc9c5c9b.zip) (actually you only need to copy shim-signed from this). It has a newer version (15.8) of the shim boot loader.

Just tried the above and it works with secure boot enabled!

**Comment by Metabolix** [comment]
Thanks @Skulldorom. Just checking: Did you have the reported problem before? If not, I'd appreciate input from someone who is affected.

**Comment by Skulldorom** [comment]
> Thanks @Skulldorom. Just checking: Did you have the reported problem before? If not, I'd appreciate input from someone who is affected.

Yeah had the same issue after updating windows 11 ![image](https://github.com/user-attachments/assets/6fc0cda2-f48b-4841-8e00-6472c6c1bcfb)

**Comment by Metabolix** [comment]
Thanks, I'll now make this a release.

**Comment by MinhTruong311** [comment]
yes, I had the same problem but when I disabled the security boot, everything became normal

**Comment by Metabolix** [comment]
> yes, I had the same problem but when I disabled the security boot, everything became normal

As stated above, this should be fixed in the latest version as of today. So have you tried version 2.5.1 yet? No need to disable secure boot.

**Comment by ProgetosDsigner** [comment]
o setup.exe não esta na pasta dos arquivos
