### ISSUE TITLE
Custom logo display issue with dualboot system

### ISSUE THREAD

**Issue by abdallahlisserbtssiolla** [Metabolix/HackBGRT#199]
Hello,
I have activated the HackBGRT tool on my computer for 1 week and frankly, there is nothing to say, it is perfect.
I have just installed the Ubuntu 22.04 system in dual boot on my computer, the problem is that when I want to boot into Windows I boot to the Windows logo and I wanted to know how to boot with my personalized logo?
Best regards.

**Comment by Metabolix** [comment]
You should be able to start HackBGRT from GRUB2 like this:

```
menuentry "Windows with HackBGRT" {
        insmod part_gpt
        insmod chain
        set root='(hd0,gpt1)'
        chainloader /EFI/HackBGRT/loader.efi
}
```

Refer to GRUB and/or [Ubuntu documentation](https://help.ubuntu.com/community/Grub2) for further instructions.

**Comment by abdallahlisserbtssiolla** [comment]
Thanks you !
