### ISSUE TITLE
IA-32 version

### ISSUE THREAD

**Issue by Koudelk** [Metabolix/HackBGRT#2]
Hi, do you plan to make a x32 version for tablets?

**Comment by Metabolix** [comment]
I don't have any IA32 devices for testing, but if someone volunteers, sure. The code already compiles fine and shouldn't contain anything too x64-specific.

If you're willing to take a risk, you can download the current x64 version and [bootia32.efi (zip)](https://github.com/Metabolix/HackBGRT/files/289708/bootia32.zip) and change all occurences of bootx64.efi with bootia32.efi in install.bat. Remember to disable Secure Boot as well.

**Comment by Koudelk** [comment]
Many thanks, it works well! I tested it on Acer Iconia W8 with 32bit W10. 
But there still shows the manufacturer's logo for about one second after reset. Is it possible to change it or simply erase it? I think that it is showed by BIOS and any booting hack will be short for that...

**Comment by Metabolix** [comment]
Thanks for testing, I'll update the installer and add this file to the official release later.

Erasing or changing the logo in the very first screen is probably impossible without hacking the firmware itself; naturally the manufacturers wouldn't like to support that. But you could see if your UEFI Setup ("BIOS" Setup, except that UEFI machines don't have real BIOS) supports the "old" text-based boot screen, which is way cooler anyway. ;)

**Comment by Metabolix** [comment]
Release 1.2.0 now supports IA-32, and the new installer will automatically choose the right version, although the installer itself hasn't been tested on IA-32.
