### ISSUE TITLE
BIOS Verification Error

### ISSUE THREAD

**Issue by noface1200** [Metabolix/HackBGRT#202]
BIOS Verification Error

**How this happens?**
Explain exactly the steps you did:

1. Installed The Newest HackBGRT Version and extract all files.
2. Completed setup. and imported the image
3. Restarted PC
4. Bios Displays An Error Message "Verification Denied" 

--- BOOT LOG START ---
Log is empty.
--- BOOT LOG END ---

**Comment by Metabolix** [comment]
Did you read [shim.md](shim.md)? If your problem is not that one, then you need to attach the install log (`setup.log`) and maybe a picture of the error as well.

**Comment by noface1200** [comment]
> Did you read [shim.md](shim.md)? If your problem is not that one, then you need to attach the install log (`setup.log`) and maybe a picture of the error as well.

got it working thanks
