### ISSUE TITLE
Where the heck is my efi drive?

### ISSUE THREAD

**Issue by GuestTheGamer** [Metabolix/HackBGRT#206]
![Capture](https://github.com/user-attachments/assets/1031ba82-8646-45a2-b99f-9ddbc70eeab5)

**Comment by Metabolix** [comment]
You are not supposed to access the EFI system partition manually to install HackBGRT. Just edit the image in the installer dir before installing. 

If you really want to, you can run `mountvol x: /s` (as admin) to access it, although you will encounter problems with permissions if you try to write any files.
