### ISSUE TITLE
iMac EFI boot windows 8.1

### ISSUE THREAD

**Issue by Claod44** [Metabolix/HackBGRT#21]
Hi,
My current windows 8.1 installation boots from efi (Apple iMac version).
I partitioned my HDD in two : Apple HFS+/FAT32 (windows intaller converted it to NTFS)
Removed the hybrid mbr with fdisk
Installed windows using Apple EFI boot.
So my hard drive is full GPT without bios emulation (I ain't use bootcamp utility).
During the first boot, the logo was here, from the second boot it was gone. I can only see spining dots.
For now I don't really know why the bootlogo is gone, bootres.dll is still here and it contains the bootlogo... But it won't shows up. I wish to fix bootres.dll, or the bootloaders.efi files, or the bgrt if Apple got one.
Does HackBGRT modify the firmware files or the booloader (microsoft efi files in EFI partition) ?
Do you know if it'll break my EFI ?

Thank you

**Comment by Metabolix** [comment]
HackBGRT doesn't modify any files or firmware, but the default installation method replaces the Windows boot loader bootmgfw.efi with HackBGRT (and makes a backup, of course).

I think Apple formats the EFI boot partition as HFS+ or APFS, which Windows probably can't access. In that case you need to install HackBGRT manually according to the multi-boot instructions (see README.md). You may need to use Linux and efibootmgr to create a boot entry for HackBGRT.
