### ISSUE TITLE
Write errors to a log file

### ISSUE THREAD

**Issue by bbottema** [Metabolix/HackBGRT#25]
During boot, I can see for a split second that HackBGRT was unable to load my bmp, but I don't get time to read the rest. Maybe write errors to a log file?

My workaround now is to record it on my phone. /edit nope, phone can't focus quickly enough.

**Comment by Metabolix** [comment]
As noted, you can use debug=1 in the config. I will think about the log file later.

**Comment by Metabolix** [comment]
Version 2.0.0 logs installation. For any boot-time problems you'll currently need to use a camera and `debug=1` in the config.
