### ISSUE TITLE
BLANK SCREEN ON BOOT PLEASE HELP!

### ISSUE THREAD

**Issue by Jaysurf88** [Metabolix/HackBGRT#29]
Hi,

I followed the instructions to the letter and now when I boot PC there is a completely blank screen until windows login page.

I can no longer access UEFI settings or anything before windows login screen, even if I choose advanced start up to fix boot issues, blue screen appears with options but nothing works after screen goes completely black.

No mouse cursor, no scrolling wheel. 

Its like now pc doesn't recognise monitors until login screen?? 

Conveniently restore wont work either its giving me an error. So the only fix im hoping will work is if someone knows exactly how to fix, its like my boot settings have been F*%ked up.

I also removed via hackbgrt setup screen, ssid removed fine. Still no change.
Please help! 

Thanks

Jay

**Comment by Metabolix** [comment]
HackBGRT does not make any permanent changes, and disabling (or uninstalling) should fix any undesired effects. HackBGRT will not and cannot prevent you from accessing UEFI settings. This shouldn't be possible at all for any program. Your computer firmware must be somehow broken. (They often are!) You can try to update (reflash) your firmware, usually with a tool provided by your vendor. If such a tool is not available or if it doesn't help, consult with your PC vendor support.
