### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by 4x0v7** [Metabolix/HackBGRT#3]
Is it possible to change the background colour? Or will it always be black

**Comment by charlesmilette** [comment]
You can always have your bitmap image span your entire screen and then change the background color of your image.

**Comment by Metabolix** [comment]
Please undestand that the BGRT only contains a single image, which the Windows boot loader draws. It is not possible to change the background color. It will be black. You can use a big image with whatever background you like, but the spinning circle thing will still have black background, so you will need some artistic skills to make it look nice.
