### ISSUE TITLE
HACKBGRT not changing OEM Boot logo.

### ISSUE THREAD

**Issue by vespper** [Metabolix/HackBGRT#32]
Hello everyone, 

I managed to install HACKBGRT and sucefully changed the windows boot logo, but i still seeing BIOS boot logo.

I mean, after pressing power on of my laptop i see a centered bios logo which is the brand of my laptop, and after few seconds the logo i changed in HACKBGRT appears at the top centered with a windows 10 circle.

The question is how do i change the bios logo too?

Thanks in advance.

**Comment by sylveon** [comment]
HackBGRT can only change the logo Windows shows, not the logo the BIOS shows before booting Windows. You'd need a BIOS modification for that (which is practically impossible on modern laptops due to the BIOS image being cryptographically verified before installation).

**Comment by AntonioCaroppos** [comment]
You can perhaps disable Fast Boot to skip having the OEM boot logo shown?
