### ISSUE TITLE
I can't boot my windows now.

### ISSUE THREAD

**Issue by EnderIce2** [Metabolix/HackBGRT#34]
I got stuck at debug... And i can't boot to windows.😭
![15510289079083338701769098781256](https://user-images.githubusercontent.com/38536866/53302667-7bb9b380-3869-11e9-93c7-98133bd050bb.jpg)

Please i need help!!!! How i can fix this?! Space bar not working, any key.... Nope, and i tried with bootrec /fixmbr or /rebuildbcd, but doesn't work

**Comment by EnderIce2** [comment]
I fixed that, if someone will have trouble with this software, you need something that can read \EFI\ system folder and when you edit config of HackBGRT use a program to BE SURE the C: drive has id of Basic Data and not UEFI System....

**Comment by Leouch1** [comment]
There is far simpler solution:
1)create USB drive with windows 10 installer
2)go to windows 10 instalation
3)repair
4)comand prompt
here:
format (letter of drive you ASSIGNED to efi partition): /FS:FAT32
bcdboot (lerrer with windows instalation partition):\windows /s (efo letter): /f UEFI

**Comment by EnderIce2** [comment]
@Leouch1 
i tried to use that solution, did worse.
