### ISSUE TITLE
Incorrect logo shows for a second

### ISSUE THREAD

**Issue by 9sqn** [Metabolix/HackBGRT#35]
I just installed the tool and it is working well, besides that when I boot, it shows the original logo for a second or two, then my one. I assume it's because I am using a Surface laptop, can someone add support for my device please?

Device: MIIX 51012ISK
OS: 10.0.17134 Build 17134

**Comment by sylveon** [comment]
This is not something HackBGRT can fix, as the original Surface logo you're
still currently seeing is part of the firmware of the Surface device, not
the Windows bootloader.

**Comment by yuukieve** [comment]
This should be closed; base UEFI firmware modifications is not something HackBGRT will *ever* be capable of doing; Intel BootGuard is enabled (and not able to be disabled) on all modern PCs and will result in a hard brick if the UEFI and ME firmware signatures don't match.
