### ISSUE TITLE
Unable to change to any other Splash.bmp than the shipped one.

### ISSUE THREAD

**Issue by ChrisPHL** [Metabolix/HackBGRT#37]
Hi Metabolix,

I tried to change the splash on two different(!) computers. For the first one the installation went through with my 1920x1080 image without any issue. (v.1.5.1) It worked OOTB.
For the second one I did exactly the same installation process but I was not able to make the new splash screen visible. So I tried a few things:
* Installation without changing the splash.bmp, used the delivered on: worked! :-)
* Installation using my splash screen with different resolutions (1920x1080, 1024x768, 800x450, 640x360): nothing worked :-(
* Installation using my splash screen (1920x1080), changing config.txt:
** x=native,y=native,path=\EFI\HackBGRT\splash.bmp
** x=0,y=0,path=\EFI\HackBGRT\splash.bmp
** resolution=0x0
** resolution=-1x-1
-->No one worked but:
Changing the resolution of my splash bitmap file seemed to change something with HackBGRT loader. I was able to see the debug output in different sizes...

Hope that information helps to get into the issue. Do you need any further information?
Any help appreciated.

Kind regards
Chris

**Comment by ChrisPHL** [comment]
Hello again!

I' found some further information about my issue:
The HackBGRT loader seems prints something like this:
```
Looking for resolution 2147483647x2147483647
Found resolution 1600x1200.
```
At this point I need to mention, the system got three destinct displays with tho following native resolutions:
VGA/RGB: 1280x1024
DVI: 1920x1080
DVI: 1280x1024

Where HackBGRT got the 1600x1200 value from is absolutely unclear. Nevertheless using the default configuration and a splash image resolution of 1280x1024 seems to work in case all displays are connected at boot time.

However, if I change the display configuration it seems a bit random if, where and how a splash screen is diplayed. :-(

I really would love to show just one splash screen on the full HD display...

Is there any way to accomplish this?

**Comment by kittuov** [comment]
I've encountered similar issue. I was able to solve this by running setup again and removing everything with "R".

then running again after copying desired splash.bmp

**Comment by Metabolix** [comment]
Currently you need to edit the file by choosing Edit from the installer. Replacing the splash.bmp in installer is not enough, you need to reinstall the files to get the image to EFI partition.

The available resolutions come from your computer firmware. If full HD is not available, there is really nothing more HackBGRT can do. The best alternative is that you choose manually a resolution and resize the image accordingly. I think the image needs to fit to the screen, or it won't be shown at all. For example, my laptop only supports 1024x768 during boot, so the image can be at most 1024x768, too.

**Comment by FPSUsername** [comment]
I can only confirm that the [Asus ROG Maximus VII Ranger](https://rog.asus.com/motherboards/rog-maximus/rog-maximus-vii-ranger-model/) motherboard outputs a max resolution of 1280x960, while I'm certanly postive that the [Gigabyte Z97X-SLI](https://www.gigabyte.com/Motherboard/GA-Z97X-SLI-rev-12) motherboard supports 1920x1080 output (BGRT isn't needed on the Gigabyte motherboard, but is on the Asus motherboard, since the boot image that can be set by AI Suite is most likely scaled to 800x600 and seems to be a lot worse than BGRT's ability to set a max resolution image)

**Comment by Metabolix** [comment]
Since the original file worked, I suspect the other files are not in the right format. Please retry with the latest release which does an automatic conversion when installing.
