### ISSUE TITLE
Boot image doesn't change (ASUS, two BGRT entries)

### ISSUE THREAD

**Issue by EXTIINCT** [Metabolix/HackBGRT#39]
I've run through the whole setup and change the image etc. and it went off without a hitch however when I rebooted my laptop. Not savvy enough to figure out why so I thought I'd give this a try.

![20190516_005534](https://user-images.githubusercontent.com/18396058/57780414-522f6a80-777c-11e9-919a-c980583b4611.jpg)

This is what debug says.

Help!

**Comment by fuzepod** [comment]
Change debug=1 to debug=0 in the config file

**Comment by Metabolix** [comment]
Apparently there's some trick with those computers which have two BGRT entries (the two `-> Replacing` lines in debug output) which I can't debug because my computer only has one such entry and for some people the current approach seems to work. Maybe some day!

**Comment by Metabolix** [comment]
For clarification, do you see the vendor logo or the Windows logo? In the latter case, please check your BMP file format and retry with the latest release.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
