### ISSUE TITLE
unattended use

### ISSUE THREAD

**Issue by JimStroomberg** [Metabolix/HackBGRT#4]
Hi, my colleagues and i love this tool.
we just cannot figure out how to make it run unattended to roll it out on all our laptops (same models).

how can i get it to pickup an image and install it without manual intervention?

With Kind Regards.

**Comment by charlesmilette** [comment]
Assuming Secure Boot is disabled:
- Extract the latest release to `[EFI System Partition]\EFI\HackBGRT\`.
- Set `boot=\EFI\Microsoft\Boot\bootmgfw.efi` in `config.txt`.
- Configure other options and boot logos as desired.
- Set `\EFI\HackBGRT\bootx64.efi` as your default boot loader with `efibootmgr` or some other EFI boot manager tool.

Step 1 to 3 could be skipped with a pre-packaged version with your custom config already set and even maybe signed for Secure Boot.

Wrap this with your preferred scripting tool (Bash, PowerShell, Batch, etc...) and run it.


Ideally the installer could either be made with some tool that supports it (InnoSetup) or updated so it supports unattended install.
