### ISSUE TITLE
Removing HackBGRT

### ISSUE THREAD

**Issue by thetechguy61705** [Metabolix/HackBGRT#40]
Hey! I'm ready and all to use this to change my boot logo, but I want to know how to remove it just in case. I'm unsure how to remove it as of now. If anybody could fill me in that would be great.

**Comment by thetechguy61705** [comment]
Nevermind, I'm so stupid

**Comment by shuvajit23** [comment]
i changed the booting font using hackgbrt now i am not being able to load my previous booting style. which was fast enough can any one help me out

**Comment by My1** [comment]
from README
> You can copy [EFI System Partition]\EFI\HackBGRT\bootmgfw-original.efi into [EFI System Partition]\EFI\Microsoft\Boot\bootmgfw.efi

**Comment by vinjo-byte** [comment]
For those who don't know: Just open the setup.exe file and then you just need to press the required to key to delete. (This key will be displayed if you open the setup.exe file)

**Comment by hooba122222** [comment]
i changed the logo startup but the windows booting is slow
