### ISSUE TITLE
Suport to change the Logo in Legacy bootloader file (Bootres.dll)

### ISSUE THREAD

**Issue by yaaaaa** [Metabolix/HackBGRT#43]

**Comment by sylveon** [comment]
There are many tools which support doing this already.

**Comment by yaaaaa** [comment]
> 
> 
> There are many tools which support doing this already.

Can You name this soft? For Win 10. 8oot logo changer is not work...

**Comment by Metabolix** [comment]
This is not in scope of my software, and will never be.
