### ISSUE TITLE
Support to change the BootStatusIndicator is identified by the red outline, and the BootStatusMessage is identified by the blue outline.

### ISSUE THREAD

**Issue by yaaaaa** [Metabolix/HackBGRT#44]
![изображение](https://user-images.githubusercontent.com/11130958/63917608-ce646a00-ca5c-11e9-9c87-ff690a32192a.png)

**Comment by Metabolix** [comment]
This is not in scope of this project. HackBGRT works 100% outside the Windows boot loader. Changing those parts would require rewriting the parts of the Windows boot loader which draws them. I suppose someone with bootres.dll and related knowledge could probably hack those; the work is probably similar but probably needs to happen on the EFI partition.
