### ISSUE TITLE
Any plans for enabling a silent installation?

### ISSUE THREAD

**Issue by aryaxo** [Metabolix/HackBGRT#49]
Would love to be able to silently install this silently, as I do not know enough about editing the EFI tables myself once the correct files are in place on the EFI partition.

Can't thank you enough for your work already!

**Comment by FREEWING-JP** [comment]
I make silent install batch file for Windows system .
It works fine in Windows 10 20H2 .

You need to edit config.txt properly in advance .

Execute following Command in Command Prompt(cmd.exe) as Administrator .
-- -- --
rem Drive name that does not currently exist in the system .
rem Generally "Y:" drives usually do not exist .
set EFI_DRIVE_LETTER=Y
set HACK_BGRT_PATH=%EFI_DRIVE_LETTER%:\EFI\HackBGRT

mountvol %EFI_DRIVE_LETTER%: /S

dir %EFI_DRIVE_LETTER%:

mkdir %HACK_BGRT_PATH%
cd %HACK_BGRT_PATH%
dir %EFI_DRIVE_LETTER%:

rem You have to need Edit config.txt , Before copying it .
rem Ex. boot=\EFI\Microsoft\Boot\bootmgfw.efi
copy config.txt Y:

rem You change to your favorite image file .
copy splash.bmp Y:

rem for 64bit System HackBGRT bootx64.efi
copy bootx64.efi Y:

dir %EFI_DRIVE_LETTER%:

mountvol %EFI_DRIVE_LETTER%: /D

rem Change boot loader to \EFI\HackBGRT\bootx64.efi
bcdedit /set {bootmgr} path \EFI\HackBGRT\bootx64.efi

rem Enjoy HackBGRT !!
-- -- --

**Comment by Metabolix** [comment]
Implemented in version 2.0.0.
