### ISSUE TITLE
Error: The EFI System Partition is not mounted.

### ISSUE THREAD

**Issue by karthikSirsikar** [Metabolix/HackBGRT#5]
Tried installing for Intel NUC. Windows 10

**Comment by Metabolix** [comment]
Check if you can mount the EFI system partition manually (i.e. run `mountvol Z: /S` as admin). If you can't mount it, it's your problem and not mine. If you think you can mount it, please attach the full output of `mountvol` (without arguments) after mounting and a full description of your attached disks and partition layouts.

**Comment by Metabolix** [comment]
Can you provide any of the information I requested? If not, I will have to close this report.

**Comment by karthikSirsikar** [comment]
Hello,

I'm really sorry for not replying for long.
The device on which i was trying has now been shipped to customers place
and i don't have another PC of same type to test.
You can close on the issue for now, if I get the device again i'll make it
sure i send the complete attachment of report to you,

Thank you :)

**Comment by Metabolix** [comment]
Ok. I'll try to make the message more informative (maybe show mountvol output automatically) in a next version.
