### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by bagou4502** [Metabolix/HackBGRT#51]
Hello

The software dont work with me 
![2020-02-07](https://user-images.githubusercontent.com/53863206/74059656-1ff02800-49f1-11ea-8ded-befb9836edf0.jpg)
![2020-02-07 (1)](https://user-images.githubusercontent.com/53863206/74059657-2088be80-49f1-11ea-9413-983082f6b642.jpg)

**Comment by ziggythehamster** [comment]
This is the same issue as https://github.com/Metabolix/HackBGRT/issues/39

**Comment by Metabolix** [comment]
Please check your BMP file format and size (should be smaller than your screen resolution, which seems to be only 1024x768 during boot). Please try with the latest release which converts images automatically to the correct format.
