### ISSUE TITLE
Can no longer get into bios

### ISSUE THREAD

**Issue by aeneas01** [Metabolix/HackBGRT#52]
used 1.5.1, saved my custom splash image as 24-bit bitmap (bmp), size of custom splash image is 275x488 395kb, disabled secure boot...

new image appears fine on restart but when screen transitions from the new splash image to the windows lockscreen image there's a bright flash right before the lockscreen image loads, as if the system was expecting the,new splash image to remain on the screen longer.

moreover, i can no longer get into bios when i reboot, none of access keys work, it immediately goes to my custom splash screen then to the windows lockscreen...

i tried option "d=disable, restore the original bootloader" in the setup, but altho i get the windows splash screen back i still get the same odd bright flash behavior as the screen transitions to the lockscreen, and i still can no longer get into the bios.

any help would be greatly appreciated.

**Comment by Metabolix** [comment]
Removing HackBGRT with the setup utility removes everything. It seems very unlikely or even impossible that HackBGRT would have any effect on your BIOS setup utility. If it does, it's a bug in your BIOS.
