### ISSUE TITLE
Double-checking: Pedantic clarification on `[EFI System Partition]`

### ISSUE THREAD

**Issue by Abscissa** [Metabolix/HackBGRT#53]
Likely very naive question, but I just wanted to be extra, extra-certain:

When the README says to extract to a particular directory in the `[EFI System Partition]`, I assume that's referring to the EFI partition that's normally hidden and un-lettered by Windows, and NOT the Windows installation drive (typically `C:`), right?

FWIW, I dual-boot, just in case that makes makes any difference.

**Comment by Metabolix** [comment]
Yes, you are correct. EFI System Partition can be manually mounted in Windows with `mountvol a: /s` where a: is the desired letter for the drive.
