### ISSUE TITLE
Someone Screwed up with the Download Links

### ISSUE THREAD

**Issue by BJ5111** [Metabolix/HackBGRT#57]
The SaveAs for BOTH "HackBGRT-1.5.1.zip" and "Source code (zip)" are the same file name: "HackBGRT-1.5.1.zip", BUT these Files ARE DIFFERENT! One would have to be Renamed on Download to Avoid a Conflict

**Comment by ziggythehamster** [comment]
*All* GitHub releases for all projects include the "source code" artifacts, which follow the convention `REPO_NAME-TAG.EXT`. This cannot be changed. Perhaps the maintainer could upload the binary with a `-bin` at the end, but this is not something that can or should be fixed otherwise.
