### ISSUE TITLE
Installed using newest Version, Shows Windows Logo(Resolution Restriction?)

### ISSUE THREAD

**Issue by helloimalastair** [Metabolix/HackBGRT#58]
Hello All,

I just installed the latest version of this program, using a custom BMP file, and when I rebooted, I saw the Debug, as I had set it to show, but I did not see the custom Boot Logo I had set, instead the screen showed the default Windows Logo. I am thinking there may be a maximum resolution for the images, but I am not sure. I have linked the output of the debug, and the image I want to use, converted to PNG so that GitHub will stop complaining. Any help is appreciated.

![splash](https://user-images.githubusercontent.com/37487746/88009269-f4588a00-cac6-11ea-95be-8c28edc6c56f.png)
![BootCapture](https://user-images.githubusercontent.com/37487746/88009080-83b16d80-cac6-11ea-8b49-ff4372327c1a.jpg)

**Comment by ziggythehamster** [comment]
This appears to be the same issue as https://github.com/Metabolix/HackBGRT/issues/39

**Comment by Metabolix** [comment]
Possible problems include bad file format (e.g. 8-bit instead of 24-bit bmp) or too big file (e.g. wider than your resolution during boot). Please try with a smaller file for debugging, and use the latest release (2.0.0) which converts images automatically to the correct format.
