### ISSUE TITLE
EFI System Partition was not found.

### ISSUE THREAD

**Issue by Cornflix244** [Metabolix/HackBGRT#60]
It couldn't find the EFI system partition although I am on Win10 64bit with UEFI an secure boot enabled.

**Comment by My1** [comment]
secure boot needs to be DIS-abled (unless you can sign the EFI yourself and add the keys to your board).

**Comment by sylveon** [comment]
Secure boot shouldn't affect the installer's ability to find the ESP though.

**Comment by Metabolix** [comment]
Well, I surely cannot fix this problem with this information. Can you see the partition in Disk Management? Can you mount the partition on command line with `mountvol a: /s`?

**Comment by Gurneet1928** [comment]
You can change the boot logo even without going into the EFI system partition. I also couldn't find the EFI location , so what i did was that when the software opens the SPLASH.BMP image , I edited that image into my spidey image with perfection and it worked perfectly .
![1920x1080-spiderman-logo-8k_1536520160](https://user-images.githubusercontent.com/68916061/154043664-f98e3b73-9daf-4238-b537-fa95a6ded931.jpg)

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
