### ISSUE TITLE
Hackbgrt not booting

### ISSUE THREAD

**Issue by Fred583** [Metabolix/HackBGRT#61]
So I installed hackbgrt and now windows is not booting. It can't find the configuration file, so it just sits at the boot screen![20200921_201834.jpg](https://user-images.githubusercontent.com/69879626/93836229-a4717d00-fc47-11ea-815b-5a63a091c153.jpg)

**Comment by Fred583** [comment]
Please help asap if possible, I need my computer for tomorrow @everyone

**Comment by Metabolix** [comment]
As the message clearly says, you can use a Windows install disk or recovery disk to fix boot issues. More information can be found at [Recovery options in Windows 10](https://support.microsoft.com/en-us/help/12415/windows-10-recovery-options) (either Use installation media to restore your PC or Use a recovery drive to restore or recover your PC).

With the limited information you have provided, it's impossible to say what has gone wrong. Apparently the installer has managed to write files on the EFI partition, so did you remove the files yourself or what?

**Comment by Fred583** [comment]
I didn't remove any of the files, I installed it and told it to restart and now it does this. My computer won't let me boot from USB, either. In the boot manager it only lists windows boot manager

**Comment by Metabolix** [comment]
You need to figure out how to boot from USB, it should be possible somehow. Or you can plug your HD to another computer and manually restore the boot files, see [README#Recovery](https://github.com/Metabolix/HackBGRT#recovery). That's really all I can say.

**Comment by Fred583** [comment]
Hmm, I have m.2 storage but ill figure it out. Thanks for the help, it means a lot

**Comment by kinesight** [comment]
@Fred583 Hey dude. If you have UEFI can you not go into BIOS and set a custom boot file by which you can choose the original from Microsoft and then use F12 (or whatever your pc uses for boot menu) then choose the new entry (Original efi of your Windows Installation) and boot Windows normally ?

 That worked for me.

**Comment by Fred583** [comment]
@kinesight I don't think so, here is my bios: ![20200922_095605.jpg](https://user-images.githubusercontent.com/69879626/93899390-e1765780-fcb9-11ea-992e-b09ddfaec80a.jpg)![20200922_095559.jpg](https://user-images.githubusercontent.com/69879626/93899407-e4714800-fcb9-11ea-9d2f-898bc54743b2.jpg)![20200922_095555.jpg](https://user-images.githubusercontent.com/69879626/93899419-e76c3880-fcb9-11ea-9fc4-ccae463d535d.jpg)![20200922_095546.jpg](https://user-images.githubusercontent.com/69879626/93899427-e9ce9280-fcb9-11ea-8ff2-6e4b06b775fa.jpg)

**Comment by Fred583** [comment]
And my boot menu (with bookable USB inserted)![20200922_095859.jpg](https://user-images.githubusercontent.com/69879626/93899746-3fa33a80-fcba-11ea-9124-abbd5471d037.jpg)

**Comment by Fred583** [comment]
I got it fixed. For anyone having the same issue, the USB had to be formatted in NTFS for my computer to show it in boot manager. I clicked repair>troubleshoot>repair disk problems. Worked like a charm. Thank you to everyone who took time to help me :)

**Comment by kinesight** [comment]
@Fred583 Seems like you don't have the feature to set a custom boot file. But glad to hear that you got it working. 

Keep Well . 👍🏻

**Comment by Fred583** [comment]
Just reinstalled it, works great. But one question. The original boot logo flashes for like half a second then it shows the hackbgrt one. Any way to fix that?

**Comment by Metabolix** [comment]
> The original boot logo flashes for like half a second then it shows the hackbgrt one. Any way to fix that?

Unfortunately no, see issue #32 for explanation.
