### ISSUE TITLE
PC not booting in any mode, stuck at Asus boot logo with no spinning dots

### ISSUE THREAD

**Issue by Minesugghitub** [Metabolix/HackBGRT#62]
Hi,

I have an ASUS X509 FB laptop. After installing HackBGRT, it doesn't turn on, only showing an ASUS boot logo.
It cannot boot neither in Windows, neither in BIOS, neither in safe mode.
Please help.
Regards,
Rosario

**Comment by TjoshgGaming** [comment]
To fix this, Get a windows recovery disk, open command prompt then type the following commands:
mountvol A: /s
A:
cd EFI
copy HackBGRT/bootmgfw-original.efi Microsoft\Boot\boot


This should fix the boot!

**Comment by Minesugghitub** [comment]
Nvm, already fixed it by using a recovery disk.
