### ISSUE TITLE
Failed to backup MS bootloader !

### ISSUE THREAD

**Issue by nin0-dev** [Metabolix/HackBGRT#65]
Hello,
When i try to install HackBGRT, I get this error : 
![image](https://user-images.githubusercontent.com/75569739/101280169-8a026680-3795-11eb-8e78-f1483745b7b9.png)
I launched HackBGRT as admin.
What i should do ?
This is my ESP's content :
![image](https://user-images.githubusercontent.com/75569739/101280267-27f63100-3796-11eb-951a-7bed968c5e7f.png)

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
