### ISSUE TITLE
I put the image in the right spot and did all the steps correctly, but it changes to the windows logo instead!

### ISSUE THREAD

**Issue by Graham124** [Metabolix/HackBGRT#67]
When i finished setup for HackBGRT and put the image in it like auto defaulted to the windows logo.

**Comment by KeyMan345** [comment]
Same on a HP Laptop. Before setup, it booted with OEM logo. After setup, it defaulted to the Windows 10 Boot Logo.

**Comment by Metabolix** [comment]
Is your image in the right format? Is it small enough? Please try the latest release and re-report this bug if it still occurs.
