### ISSUE TITLE
works perfectly but still the old logo visible for a short while before new logo appears

### ISSUE THREAD

**Issue by michel437** [Metabolix/HackBGRT#70]
HackBGRT works fine but do you know if there is a way not to see the original logo before the new one appears at startup? when i boot my lattepanda, the lattepanda logo appears a short while and mine appears. how to avoid to see the lattepanda logo?

**Comment by My1** [comment]
likely that's from the bios/uefi while doing POST, unless your manufacturer actually allows replacing that, you likely cannot stop that.

**Comment by Metabolix** [comment]
Your computer shows the logo before loading HackBGRT. Unfortunately that can't be changed without some firmware patch.
