### ISSUE TITLE
Once I have done installing hackBGRT with my new logo on, can I turn on secure boot again?

### ISSUE THREAD

**Issue by Clarkispioneer** [Metabolix/HackBGRT#73]
I downloaded the HackBGRT software and I want to change my logo. Before I install, I just want to know whether it's ok to enable the secure boot after I have HackBGRT installed in my computer.

**Comment by ExeCsrss** [comment]
No, keep secure boot off or your computer won't boot!

**Comment by Clarkispioneer** [comment]
@ExeCsrss 

Ok thx
