### ISSUE TITLE
Another issue here about the boot logo when I uninstall and startup my PC again.

### ISSUE THREAD

**Issue by Clarkispioneer** [Metabolix/HackBGRT#74]
When I try to disable HackBGRT or install, I can see the changed boot logo along with the original logo. Does it mean I can still turn back on secure boot?

If I miss something from here, please immediately tell me.

Please help!

Thx.

**Comment by pepanee** [comment]
This is from my experience! Only use this information as a reference. 

What I noticed is that, assuming I have HackBGRT enabled, I gotta disable Secure Boot in order for Windows to show my custom logo, and to boot into Windows. 
Now let's say I go back into the BIOS settings and enable Secure Boot, while the HackBGRT is still modified to use my custom logo, I get an error message stating that Windows cannot boot. And if I restart the computer, go back into the BIOS settings, and disable Secure Boot again, then the computer will start up again with my custom logo.

**Comment by ZacLiiscool** [comment]
yes same same problem plz help

**Comment by Metabolix** [comment]
If you disable HackBGRT with the setup program and the setup says it's done, then yes, it should be gone and you can use Secure Boot again. Also, you shouldn't see the image anymore after uninstalling, so I don't know how that's even possible. Please use the version 2.0.0 setup for uninstalling and provide the `setup.log` file in case of any problems.
