### ISSUE TITLE
Error: The EFI System Partition is not mounted

### ISSUE THREAD

**Issue by Vaissai** [Metabolix/HackBGRT#8]
hello i am sai. I have windows 10 32bit os. I tried to change boot logo by HackBGRT-1.3.0. But i cant install. Because while i install setup.exe error is showing like this "The EFI System Partition is not mounted." I know the reason because i have MBR System Partition so i cant install without convert to GPT System Partition (efi) from MBR. So how can change boot logo by HackBGRT-1.3.0 to windows 10 32bit os? Please help me..

**Comment by charlesmilette** [comment]
If you boot using MBR you can't change the logo with HackBGRT, you need to
use something like this:
http://www.intowindows.com/changing-windows-8-1-boot-logo-using-8oot-logo-changer-tool/

**Comment by Vaissai** [comment]
Thanks for reply. I tried. But 8oot Logo Changer is not working properly to windows 10 32bit os.

**Comment by Metabolix** [comment]
HackBGRT is only for EFI and GPT, and this will not change.
