### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Hypenord** [Metabolix/HackBGRT#82]
Normally, my pc shows my manufacturer's (Lenovo) logo. I wanted to change it, and then, i used HackBGRT. Everything looked fine at installion but when i rebooted, instead of logo i gave, its changed to windows default logo (btw im using Windows 11). There is what i get when i enabled debug mode:
![photo_2021-07-10_18-23-25](https://user-images.githubusercontent.com/78219975/125169217-d4c3e100-e1b1-11eb-9c61-120de1ee4aa6.jpg)

System Information:
![Screenshot_1](https://user-images.githubusercontent.com/78219975/125169233-ead1a180-e1b1-11eb-990d-6822b8b5c649.png)

My config.txt:
[config.txt](https://github.com/Metabolix/HackBGRT/files/6795573/config.txt)

bcdedit result:
![Screenshot_2](https://user-images.githubusercontent.com/78219975/125169277-16548c00-e1b2-11eb-9dda-593e043ae151.png)

Icon i used (Zipped it as github not supports .bmp):
[hydro.zip](https://github.com/Metabolix/HackBGRT/files/6795578/hydro.zip)

Can someone help me about it?

**Comment by Metabolix** [comment]
Your bmp is not 24-bit. Please try with version 2.0.0 which converts the image automatically when installing. (You can even use a PNG or such, and it will be converted when installing.)
