### ISSUE TITLE
HackBGRT on WinPE

### ISSUE THREAD

**Issue by 5cover** [Metabolix/HackBGRT#83]
Hello
I would like to change the boot logo of the Windows 10 installtion environment. I tried to do it manually, but there is no bootmgfw.efi, only cdboot and cdboot_noprompt.efi in the efi\microsoft\boot subfolder of the Windows 10 iso. I tried modifying bootres.dll but it resuled in a black boot screen. So i don't know what to do.

**Comment by 2096779623** [comment]
HackBGRT cannot be opened in WinPE environment,But I don’t know if I can use it to modify .ISO files.

**Comment by thediscover22450** [comment]
Yes, it's what i want to do.

**Comment by Metabolix** [comment]
You can replace any .efi file with HackBGRT.efi (remember backup!) and then point the `boot=` option to the original .efi file, so technically it should work just as well (assuming that WinPE shows the logo from UEFI).
