### ISSUE TITLE
Short flash of another custom splash

### ISSUE THREAD

**Issue by Cris--** [Metabolix/HackBGRT#84]
Hi, HackBGRT nearly works perfect here on my Lenovo P51.
First i see the Lenovo Post BIOS Logo.
Then a random one of my 5 splash bmp's but before the W10 logon screen there shortly flash another one of my splashes (2-3s).
Hope the description is clear enogh to understand the culprit.

[config.txt](https://github.com/Metabolix/HackBGRT/files/6946021/config.txt)

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot disabled?

**Comment by Metabolix** [comment]
HackBGRT sets the image only once, so if you see two images, it means you are running HackBGRT twice and some other boot loader in between. This could easily happen with some custom configuration (such as HackBGRT  => Grub => HackBGRT => Windows), but if you don't have anything like that, then it's a mystery. Maybe version 2.0.0 with a proper EFI boot entry helps.

**Comment by Metabolix** [comment]
Insufficient information but sounds like user configuration error. Closing.
