### ISSUE TITLE
Not working on Surface RT

### ISSUE THREAD

**Issue by MASONNET1** [Metabolix/HackBGRT#85]
[https://drive.google.com/file/d/1ivy4B3FoW0Zw7Aqu5OudIFgYqBji3vXY/view?usp=drivesdk](https://drive.google.com/file/d/1ivy4B3FoW0Zw7Aqu5OudIFgYqBji3vXY/view?usp=drivesdk)

**Comment by MASONNET1** [comment]
[https://drive.google.com/file/d/1-bQcQ-EbT5NTDolgr9sERV7Qc7u2VwsX/view?usp=drivesdk](https://drive.google.com/file/d/1-bQcQ-EbT5NTDolgr9sERV7Qc7u2VwsX/view?usp=drivesdk)

**Comment by MASONNET1** [comment]
[https://drive.google.com/file/d/1wupa_aAR-NIJN-gyyJROCE6wsWu1-Gs3/view?usp=drivesdk](https://drive.google.com/file/d/1wupa_aAR-NIJN-gyyJROCE6wsWu1-Gs3/view?usp=drivesdk)

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot disabled?

**Comment by Metabolix** [comment]
ARM is indeed not supported.
