### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by acordtag** [Metabolix/HackBGRT#89]
Boot splash is configured to only display on the default view, so on a windows tablet it would be portrait. How can the boot screen be rotated?

**Comment by sylveon** [comment]
Rotate the picture?

**Comment by acordtag** [comment]
Thanks for your replay.
yes; ended up doing that, but picture is too small since I can only use half left of the screen.
Any way to rotate using  EFI tables?

**Comment by Metabolix** [comment]
It's indeed possible, and changing the orientation is implemented in version 2.0.0.
