### ISSUE TITLE
Let's Assume The Worst Case Scenario

### ISSUE THREAD

**Issue by pepanee** [Metabolix/HackBGRT#90]
Sorry if this has already been covered, but I have a question.

Let's assume that I enable HackBGRT to have my own custom logo, and I have Secure Boot enabled, then obviously the computer is not going to start up, and will say a message that it cannot boot. Now let's say that I disable Secure Boot, and I happen to get that same exact message, this would imply that the computer is completely unbootable anymore. 

Let's say this scenario happens, how would I be able to repair the original Windows boot settings?

(After every big Windows update, the boot sector seems to go back to the default uncustomized boot logo, and I would have to re-enable HackBGRT. But before enabling HackBGRT, my heart skips a beat thinking of the possibility that the computer won't be able to boot up if I use HackBGRT to re-enable my custom logo.)

Thanks.

**Comment by OverloadedTech** [comment]
I think you might need to reinstall the entire OS. But I am not sure

**Comment by InukaAsith** [comment]
Reinstalling boot manager will fix it as i guess

**Comment by Metabolix** [comment]
You would boot from Windows installation media (repair partition / USB / etc.) and run Startup Repair, probably.
