### ISSUE TITLE
Uninstalling Secure Boot Question

### ISSUE THREAD

**Issue by OverloadedTech** [Metabolix/HackBGRT#91]
Hi, i have a simple question: If i uninstall HackBGRT and also with it the custom logo can i after reactivate the secure boot option from my PC bios or it will not boot up anymore also after uninstalling?

**Comment by Metabolix** [comment]
You cannot have both HackBGRT and Secure Boot enabled. It's not actually disabled to allow installing, it's disabled to allow use.
