### ISSUE TITLE
won't work in windows 11

### ISSUE THREAD

**Issue by PaxtonPenguin** [Metabolix/HackBGRT#93]
i have a lenovo laptop and when i restart after it is installed, it comes up with the default windows 11 boot logo insted of my or lenovo's logo.
please help me.

**Comment by Wishcometrue100** [comment]
im having the same issue to.

**Comment by Gurneet1928** [comment]
Working for me correctly on windows 11 , added a spidey logo :) 
![1920x1080-spiderman-logo-8k_1536520160](https://user-images.githubusercontent.com/68916061/154042469-6266624e-7029-4a32-b41f-4ec83490ddaf.jpg)

![image](https://user-images.githubusercontent.com/68916061/154042585-4e94126e-2e5d-446e-8098-52762d1d16af.png)

**Comment by Wishcometrue100** [comment]
cool

**Comment by ivankrstev** [comment]
Make sure when the MSPaint is open to go to save as and save it as 24-bit BMP. And then just click close.
That worked for me.

**Comment by Metabolix** [comment]
I can't really (efficiently) help with issues with some specific laptop without having access to that laptop. It requires some hands-on debugging.
