### ISSUE TITLE
HackBGRT Error: Failed to detect MS boot loader!

### ISSUE THREAD

**Issue by Rudra9127** [Metabolix/HackBGRT#94]
**I'm new in this but when I tried to open hackbgrt and used it the prompt said**

HackBGRT installer version: v1.5.1
EFI System Partition location is A:
Secure Boot is disabled, good!
Error: Failed to detect MS boot loader!
Press any key to quit.

please help me!

**Comment by Rudra9127** [comment]
please help!

**Comment by lol90101** [comment]
what version of HACKBGRT are you using?

**Comment by gh-doot** [comment]
> do you know how to replicate this?

I am unsure, but it appears to happen and is a real issue since I have also encountered the same issue:
```
HackBGRT installer version: v1.5.1
EFI System Partition location is A:
Secure Boot is disabled, good!
Error: Failed to detect MS boot loader!
Press any key to quit.
```

**Comment by Metabolix** [comment]
Please try the new release. If you run into problems during installation, please provide `setup.log` file for any further assistance.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
