### ISSUE TITLE
Boot File Reverting

### ISSUE THREAD

**Issue by EhanChowdhury** [Metabolix/HackBGRT#95]
When I Boot It Says Reverting Boot File To bootmgfw-original.efi
Then It Says
ESC To Exit, Any Key To Boot

**Comment by Metabolix** [comment]
I'm sure it says something else before that, either "Boot path not specified" or "Failed to load application <some_path_here>".

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot disabled ?

**Comment by EhanChowdhury** [comment]
Mahh i dont need it any more :)
