### ISSUE TITLE
how to animate an image?

### ISSUE THREAD

**Issue by streemline** [Metabolix/HackBGRT#98]
How can you make your own image animation?
Как можно сделать свою анимацию изображения?

**Comment by SebastianCompany-Norway** [comment]
Sorry, but that is not possible. If yu need help, watch this video: https://www.google.no/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj3_v_Pk9z3AhXolIsKHafbDtsQtwJ6BAgEEAI&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9r6BkmtvCB4&usg=AOvVaw3zRRLgA4hY0ai58dn9Z7vy

**Comment by Metabolix** [comment]
It is not possible, HackBGRT does not draw anything, Windows draws it. You need to hack Microsoft boot loader to do this.
